'use strict';

addArrayHexList({
  name: 'test 2',
  comment: 'testing continues',
  data: {
    '00': [ '%', 'red', 'underline' ],
    '01': [ '■', 'red', 'underline' ],
    '02': [ '🡇', 'red', 'underline' ],
    '03': [ '🕭', 'red', 'underline' ],
    '04': [ '✂', 'red', 'underline' ],
    '05': [ '♛', 'red', 'underline' ],
    '06': [ '⑨', 'red' ],
    '07': [ '🕿', 'red' ],
    '08': [ '⑤', 'red' ],
    '09': [ '⑨', 'green', 'bold' ],
    '10': [ '', 'red' ],
    '11': [ '■', 'red' ],
    '12': [ '⑦', 'blue', 'underline-italic' ],
    '13': [ '🖢', 'blue', 'underline-italic' ],
    '14': [ '⬥', 'blue', 'underline-italic' ],
    '15': [ '①', 'blue', 'underline-italic' ],
    '16': [ '2', 'blue', 'underline-italic' ],
    '17': [ '👁', 'blue', 'underline-italic' ],
    '18': [ '←', 'blue', 'underline-italic' ],
    '19': [ '⑤', 'blue', 'underline-italic' ],
    '20': [ '', 'blue' ],
    '21': [ '←', 'blue' ],
    '22': [ '🕪', 'blue' ],
    '23': [ '✉', 'blue' ],
    '24': [ '✈', 'blue' ],
    '25': [ '🕪', 'green' ],
    '26': [ '🛧', 'green' ],
    '27': [ '🏠', 'green' ],
    '28': [ '←', 'green' ],
    '29': [ '#', 'green' ],
    '30': [ '', 'green' ],
    '31': [ '①', 'green' ],
    '32': [ 'aa', 'green' ],
    '33': [ '3', 'green', 'special' ],
    '34': [ 'b', 'green', 'special' ],
    '35': [ 'A', 'green', 'special' ],
    '36': [ '🛧', 'green', 'special' ],
    '37': [ '❤', 'yellow', 'special' ],
    '38': [ '♥', 'yellow', 'special' ],
    '39': [ '♥', 'yellow', 'special' ],
    '40': [ '♥', 'yellow', 'special' ],
    '41': [ '①', 'yellow', 'special' ],
    '42': [ '②', 'yellow' ],
  },
});