// exported at 9/23/2018, 7:31:45 PM
'use strict';

addArrayHexList({
  name: 'IdentiAddress II',
  author: 'Hus',
  comment: 'Inspired by IdentiAddress of @Cygnusfear, check out https://github.com/Cygnusfear/IdentiAddress',
  number: '402',
  data: {
    '00': [ '00', 'bg-black', ],
    '01': [ '01', 'bg-black', ],
    '02': [ '02', 'bg-black', ],
    '03': [ '03', 'bg-black', ],
    '04': [ '04', 'bg-black', ],
    '05': [ '05', 'bg-black', ],
    '06': [ '06', 'bg-black', ],
    '07': [ '07', 'bg-black', ],
    '08': [ '08', 'bg-black', ],
    '09': [ '09', 'bg-black', ],
    '0a': [ '0a', 'bg-black', ],
    '0b': [ '0b', 'bg-black', ],
    '0c': [ '0c', 'bg-black', ],
    '0d': [ '0d', 'bg-black', ],
    '0e': [ '0e', 'bg-black', ],
    '0f': [ '0f', 'bg-black', ],
    '10': [ '10', 'bg-gray', ],
    '11': [ '11', 'bg-gray', ],
    '12': [ '12', 'bg-gray', ],
    '13': [ '13', 'bg-gray', ],
    '14': [ '14', 'bg-gray', ],
    '15': [ '15', 'bg-gray', ],
    '16': [ '16', 'bg-gray', ],
    '17': [ '17', 'bg-gray', ],
    '18': [ '18', 'bg-gray', ],
    '19': [ '19', 'bg-gray', ],
    '1a': [ '1a', 'bg-gray', ],
    '1b': [ '1b', 'bg-gray', ],
    '1c': [ '1c', 'bg-gray', ],
    '1d': [ '1d', 'bg-gray', ],
    '1e': [ '1e', 'bg-gray', ],
    '1f': [ '1f', 'bg-gray', ],
    '20': [ '20', 'bg-red', ],
    '21': [ '21', 'bg-red', ],
    '22': [ '22', 'bg-red', ],
    '23': [ '23', 'bg-red', ],
    '24': [ '24', 'bg-red', ],
    '25': [ '25', 'bg-red', ],
    '26': [ '26', 'bg-red', ],
    '27': [ '27', 'bg-red', ],
    '28': [ '28', 'bg-red', ],
    '29': [ '29', 'bg-red', ],
    '2a': [ '2a', 'bg-red', ],
    '2b': [ '2b', 'bg-red', ],
    '2c': [ '2c', 'bg-red', ],
    '2d': [ '2d', 'bg-red', ],
    '2e': [ '2e', 'bg-red', ],
    '2f': [ '2f', 'bg-red', ],
    '30': [ '30', 'bg-orange', ],
    '31': [ '31', 'bg-orange', ],
    '32': [ '32', 'bg-orange', ],
    '33': [ '33', 'bg-orange', ],
    '34': [ '34', 'bg-orange', ],
    '35': [ '35', 'bg-orange', ],
    '36': [ '36', 'bg-orange', ],
    '37': [ '37', 'bg-orange', ],
    '38': [ '38', 'bg-orange', ],
    '39': [ '39', 'bg-orange', ],
    '3a': [ '3a', 'bg-orange', ],
    '3b': [ '3b', 'bg-orange', ],
    '3c': [ '3c', 'bg-orange', ],
    '3d': [ '3d', 'bg-orange', ],
    '3e': [ '3e', 'bg-orange', ],
    '3f': [ '3f', 'bg-orange', ],
    '40': [ '40', 'bg-yellow', ],
    '41': [ '41', 'bg-yellow', ],
    '42': [ '42', 'bg-yellow', ],
    '43': [ '43', 'bg-yellow', ],
    '44': [ '44', 'bg-yellow', ],
    '45': [ '45', 'bg-yellow', ],
    '46': [ '46', 'bg-yellow', ],
    '47': [ '47', 'bg-yellow', ],
    '48': [ '48', 'bg-yellow', ],
    '49': [ '49', 'bg-yellow', ],
    '4a': [ '4a', 'bg-yellow', ],
    '4b': [ '4b', 'bg-yellow', ],
    '4c': [ '4c', 'bg-yellow', ],
    '4d': [ '4d', 'bg-yellow', ],
    '4e': [ '4e', 'bg-yellow', ],
    '4f': [ '4f', 'bg-yellow', ],
    '50': [ '50', 'bg-green', ],
    '51': [ '51', 'bg-green', ],
    '52': [ '52', 'bg-green', ],
    '53': [ '53', 'bg-green', ],
    '54': [ '54', 'bg-green', ],
    '55': [ '55', 'bg-green', ],
    '56': [ '56', 'bg-green', ],
    '57': [ '57', 'bg-green', ],
    '58': [ '58', 'bg-green', ],
    '59': [ '59', 'bg-green', ],
    '5a': [ '5a', 'bg-green', ],
    '5b': [ '5b', 'bg-green', ],
    '5c': [ '5c', 'bg-green', ],
    '5d': [ '5d', 'bg-green', ],
    '5e': [ '5e', 'bg-green', ],
    '5f': [ '5f', 'bg-green', ],
    '60': [ '60', 'bg-blue', ],
    '61': [ '61', 'bg-blue', ],
    '62': [ '62', 'bg-blue', ],
    '63': [ '63', 'bg-blue', ],
    '64': [ '64', 'bg-blue', ],
    '65': [ '65', 'bg-blue', ],
    '66': [ '66', 'bg-blue', ],
    '67': [ '67', 'bg-blue', ],
    '68': [ '68', 'bg-blue', ],
    '69': [ '69', 'bg-blue', ],
    '6a': [ '6a', 'bg-blue', ],
    '6b': [ '6b', 'bg-blue', ],
    '6c': [ '6c', 'bg-blue', ],
    '6d': [ '6d', 'bg-blue', ],
    '6e': [ '6e', 'bg-blue', ],
    '6f': [ '6f', 'bg-blue', ],
    '70': [ '70', 'bg-purple', ],
    '71': [ '71', 'bg-purple', ],
    '72': [ '72', 'bg-purple', ],
    '73': [ '73', 'bg-purple', ],
    '74': [ '74', 'bg-purple', ],
    '75': [ '75', 'bg-purple', ],
    '76': [ '76', 'bg-purple', ],
    '77': [ '77', 'bg-purple', ],
    '78': [ '78', 'bg-purple', ],
    '79': [ '79', 'bg-purple', ],
    '7a': [ '7a', 'bg-purple', ],
    '7b': [ '7b', 'bg-purple', ],
    '7c': [ '7c', 'bg-purple', ],
    '7d': [ '7d', 'bg-purple', ],
    '7e': [ '7e', 'bg-purple', ],
    '7f': [ '7f', 'bg-purple', ],
    '80': [ '80', 'bg-black', 'underline' ],
    '81': [ '81', 'bg-black', 'underline' ],
    '82': [ '82', 'bg-black', 'underline' ],
    '83': [ '83', 'bg-black', 'underline' ],
    '84': [ '84', 'bg-black', 'underline' ],
    '85': [ '85', 'bg-black', 'underline' ],
    '86': [ '86', 'bg-black', 'underline' ],
    '87': [ '87', 'bg-black', 'underline' ],
    '88': [ '88', 'bg-black', 'underline' ],
    '89': [ '89', 'bg-black', 'underline' ],
    '8a': [ '8a', 'bg-black', 'underline' ],
    '8b': [ '8b', 'bg-black', 'underline' ],
    '8c': [ '8c', 'bg-black', 'underline' ],
    '8d': [ '8d', 'bg-black', 'underline' ],
    '8e': [ '8e', 'bg-black', 'underline' ],
    '8f': [ '8f', 'bg-black', 'underline' ],
    '90': [ '90', 'bg-gray', 'underline' ],
    '91': [ '91', 'bg-gray', 'underline' ],
    '92': [ '92', 'bg-gray', 'underline' ],
    '93': [ '93', 'bg-gray', 'underline' ],
    '94': [ '94', 'bg-gray', 'underline' ],
    '95': [ '95', 'bg-gray', 'underline' ],
    '96': [ '96', 'bg-gray', 'underline' ],
    '97': [ '97', 'bg-gray', 'underline' ],
    '98': [ '98', 'bg-gray', 'underline' ],
    '99': [ '99', 'bg-gray', 'underline' ],
    '9a': [ '9a', 'bg-gray', 'underline' ],
    '9b': [ '9b', 'bg-gray', 'underline' ],
    '9c': [ '9c', 'bg-gray', 'underline' ],
    '9d': [ '9d', 'bg-gray', 'underline' ],
    '9e': [ '9e', 'bg-gray', 'underline' ],
    '9f': [ '9f', 'bg-gray', 'underline' ],
    'a0': [ 'a0', 'bg-red', 'underline' ],
    'a1': [ 'a1', 'bg-red', 'underline' ],
    'a2': [ 'a2', 'bg-red', 'underline' ],
    'a3': [ 'a3', 'bg-red', 'underline' ],
    'a4': [ 'a4', 'bg-red', 'underline' ],
    'a5': [ 'a5', 'bg-red', 'underline' ],
    'a6': [ 'a6', 'bg-red', 'underline' ],
    'a7': [ 'a7', 'bg-red', 'underline' ],
    'a8': [ 'a8', 'bg-red', 'underline' ],
    'a9': [ 'a9', 'bg-red', 'underline' ],
    'aa': [ 'aa', 'bg-red', 'underline' ],
    'ab': [ 'ab', 'bg-red', 'underline' ],
    'ac': [ 'ac', 'bg-red', 'underline' ],
    'ad': [ 'ad', 'bg-red', 'underline' ],
    'ae': [ 'ae', 'bg-red', 'underline' ],
    'af': [ 'af', 'bg-red', 'underline' ],
    'b0': [ 'b0', 'bg-orange', 'underline' ],
    'b1': [ 'b1', 'bg-orange', 'underline' ],
    'b2': [ 'b2', 'bg-orange', 'underline' ],
    'b3': [ 'b3', 'bg-orange', 'underline' ],
    'b4': [ 'b4', 'bg-orange', 'underline' ],
    'b5': [ 'b5', 'bg-orange', 'underline' ],
    'b6': [ 'b6', 'bg-orange', 'underline' ],
    'b7': [ 'b7', 'bg-orange', 'underline' ],
    'b8': [ 'b8', 'bg-orange', 'underline' ],
    'b9': [ 'b9', 'bg-orange', 'underline' ],
    'ba': [ 'ba', 'bg-orange', 'underline' ],
    'bb': [ 'bb', 'bg-orange', 'underline' ],
    'bc': [ 'bc', 'bg-orange', 'underline' ],
    'bd': [ 'bd', 'bg-orange', 'underline' ],
    'be': [ 'be', 'bg-orange', 'underline' ],
    'bf': [ 'bf', 'bg-orange', 'underline' ],
    'c0': [ 'c0', 'bg-yellow', 'underline' ],
    'c1': [ 'c1', 'bg-yellow', 'underline' ],
    'c2': [ 'c2', 'bg-yellow', 'underline' ],
    'c3': [ 'c3', 'bg-yellow', 'underline' ],
    'c4': [ 'c4', 'bg-yellow', 'underline' ],
    'c5': [ 'c5', 'bg-yellow', 'underline' ],
    'c6': [ 'c6', 'bg-yellow', 'underline' ],
    'c7': [ 'c7', 'bg-yellow', 'underline' ],
    'c8': [ 'c8', 'bg-yellow', 'underline' ],
    'c9': [ 'c9', 'bg-yellow', 'underline' ],
    'ca': [ 'ca', 'bg-yellow', 'underline' ],
    'cb': [ 'cb', 'bg-yellow', 'underline' ],
    'cc': [ 'cc', 'bg-yellow', 'underline' ],
    'cd': [ 'cd', 'bg-yellow', 'underline' ],
    'ce': [ 'ce', 'bg-yellow', 'underline' ],
    'cf': [ 'cf', 'bg-yellow', 'underline' ],
    'd0': [ 'd0', 'bg-green', 'underline' ],
    'd1': [ 'd1', 'bg-green', 'underline' ],
    'd2': [ 'd2', 'bg-green', 'underline' ],
    'd3': [ 'd3', 'bg-green', 'underline' ],
    'd4': [ 'd4', 'bg-green', 'underline' ],
    'd5': [ 'd5', 'bg-green', 'underline' ],
    'd6': [ 'd6', 'bg-green', 'underline' ],
    'd7': [ 'd7', 'bg-green', 'underline' ],
    'd8': [ 'd8', 'bg-green', 'underline' ],
    'd9': [ 'd9', 'bg-green', 'underline' ],
    'da': [ 'da', 'bg-green', 'underline' ],
    'db': [ 'db', 'bg-green', 'underline' ],
    'dc': [ 'dc', 'bg-green', 'underline' ],
    'dd': [ 'dd', 'bg-green', 'underline' ],
    'de': [ 'de', 'bg-green', 'underline' ],
    'df': [ 'df', 'bg-green', 'underline' ],
    'e0': [ 'e0', 'bg-blue', 'underline' ],
    'e1': [ 'e1', 'bg-blue', 'underline' ],
    'e2': [ 'e2', 'bg-blue', 'underline' ],
    'e3': [ 'e3', 'bg-blue', 'underline' ],
    'e4': [ 'e4', 'bg-blue', 'underline' ],
    'e5': [ 'e5', 'bg-blue', 'underline' ],
    'e6': [ 'e6', 'bg-blue', 'underline' ],
    'e7': [ 'e7', 'bg-blue', 'underline' ],
    'e8': [ 'e8', 'bg-blue', 'underline' ],
    'e9': [ 'e9', 'bg-blue', 'underline' ],
    'ea': [ 'ea', 'bg-blue', 'underline' ],
    'eb': [ 'eb', 'bg-blue', 'underline' ],
    'ec': [ 'ec', 'bg-blue', 'underline' ],
    'ed': [ 'ed', 'bg-blue', 'underline' ],
    'ee': [ 'ee', 'bg-blue', 'underline' ],
    'ef': [ 'ef', 'bg-blue', 'underline' ],
    'f0': [ 'f0', 'bg-purple', 'underline' ],
    'f1': [ 'f1', 'bg-purple', 'underline' ],
    'f2': [ 'f2', 'bg-purple', 'underline' ],
    'f3': [ 'f3', 'bg-purple', 'underline' ],
    'f4': [ 'f4', 'bg-purple', 'underline' ],
    'f5': [ 'f5', 'bg-purple', 'underline' ],
    'f6': [ 'f6', 'bg-purple', 'underline' ],
    'f7': [ 'f7', 'bg-purple', 'underline' ],
    'f8': [ 'f8', 'bg-purple', 'underline' ],
    'f9': [ 'f9', 'bg-purple', 'underline' ],
    'fa': [ 'fa', 'bg-purple', 'underline' ],
    'fb': [ 'fb', 'bg-purple', 'underline' ],
    'fc': [ 'fc', 'bg-purple', 'underline' ],
    'fd': [ 'fd', 'bg-purple', 'underline' ],
    'fe': [ 'fe', 'bg-purple', 'underline' ],
    'ff': [ 'ff', 'bg-purple', 'underline' ],
  },
});