// exported at 9/23/2018, 7:26:37 PM
'use strict';

addArrayHexList({
  name: 'Geometric & Common Shapes',
  author: 'Hus',
  comment: 'Same as Momcode-220 but using FA',
  number: '220A',
  data: {
    '00': [ ' ', 'black fas fa-plus', 'underline' ],
    '01': [ ' ', 'black fas fa-circle', 'underline' ],
    '02': [ ' ', 'fas fa-heart black', 'underline' ],
    '03': [ ' ', 'fas fa-triangle black', 'underline' ],
    '04': [ ' ', 'fas fa-square black', 'underline' ],
    '05': [ ' ', 'fas fa-star black', 'underline' ],
    '06': [ ' ', 'fas fa-arrow-left black', 'underline' ],
    '07': [ ' ', 'fas fa-arrow-up black', 'underline' ],
    '08': [ ' ', 'fas fa-arrow-right black', 'underline' ],
    '09': [ ' ', 'fas fa-arrow-down black', 'underline' ],
    '0a': [ ' ', 'fas fa-circle red', 'underline' ],
    '0b': [ ' ', 'fas fa-circle orange', 'underline' ],
    '0c': [ ' ', 'fas fa-circle yellow', 'underline' ],
    '0d': [ ' ', 'fas fa-circle green', 'underline' ],
    '0e': [ ' ', 'fas fa-circle blue', 'underline' ],
    '0f': [ ' ', 'fas fa-circle purple', 'underline' ],
    '10': [ '', 'black fas fa-plus', ],
    '11': [ ' ', 'fas fa-circle black fas fa-circle', ],
    '12': [ ' ', 'fas fa-heart black', ],
    '13': [ '▲', 'black', ],
    '14': [ ' ', 'fas fa-square black', ],
    '15': [ ' ', 'fas fa-star black', ],
    '16': [ ' ', 'fas fa-arrow-left black', ],
    '17': [ ' ', 'fas fa-arrow-up black', ],
    '18': [ ' ', 'fas fa-arrow-right black', ],
    '19': [ ' ', 'fas fa-arrow-down black', ],
    '1a': [ '', 'red fas fa-plus', 'underline' ],
    '1b': [ '', 'orange fas fa-plus', 'underline' ],
    '1c': [ '', 'yellow fas fa-plus', 'underline' ],
    '1d': [ '', 'green fas fa-plus', 'underline' ],
    '1e': [ '', 'blue fas fa-plus', 'underline' ],
    '1f': [ '', 'purple fas fa-plus', 'underline' ],
    '20': [ '', 'gray fas fa-plus', ],
    '21': [ ' ', 'fas fa-circle gray fas fa-circle', ],
    '22': [ ' ', 'fas fa-heart gray', ],
    '23': [ '▲', 'gray', ],
    '24': [ ' ', 'fas fa-square gray', ],
    '25': [ ' ', 'fas fa-star gray', ],
    '26': [ ' ', 'fas fa-arrow-left gray', ],
    '27': [ ' ', 'fas fa-arrow-up gray', ],
    '28': [ ' ', 'fas fa-arrow-right gray', ],
    '29': [ ' ', 'fas fa-arrow-down gray', ],
    '2a': [ ' ', 'fas fa-heart red', 'underline' ],
    '2b': [ ' ', 'fas fa-heart orange', 'underline' ],
    '2c': [ ' ', 'fas fa-heart yellow', 'underline' ],
    '2d': [ ' ', 'fas fa-heart green', 'underline' ],
    '2e': [ ' ', 'fas fa-heart blue', 'underline' ],
    '2f': [ ' ', 'fas fa-heart purple', 'underline' ],
    '30': [ ' ', 'fas fa-plus white', ],
    '31': [ ' ', 'fas fa-circle white fas fa-circle', ],
    '32': [ ' ', 'fas fa-heart white', ],
    '33': [ '▲', 'white', ],
    '34': [ ' ', 'fas fa-square white', ],
    '35': [ ' ', 'fas fa-star white', ],
    '36': [ ' ', 'fas fa-arrow-left white', ],
    '37': [ ' ', 'fas fa-arrow-up white', ],
    '38': [ ' ', 'fas fa-arrow-right white', ],
    '39': [ ' ', 'fas fa-arrow-down white', ],
    '3a': [ '▲', 'red', 'underline' ],
    '3b': [ '▲', 'orange', 'underline' ],
    '3c': [ '▲', 'yellow', 'underline' ],
    '3d': [ '▲', 'green', 'underline' ],
    '3e': [ '▲', 'blue', 'underline' ],
    '3f': [ '▲', 'purple', 'underline' ],
    '40': [ ' ', 'fas fa-yin-yang purple', ],
    '41': [ ' ', 'fas fa-umbrella purple', ],
    '42': [ ' ', 'fas fa-phone purple', 'small' ],
    '43': [ '⁂', 'purple', 'small' ],
    '44': [ ' ', 'fas fa-sun purple', ],
    '45': [ '✿', 'purple', ],
    '46': [ ' ', 'fas fa-cut purple', ],
    '47': [ ' ', 'fas fa-volume-up purple', ],
    '48': [ ' ', 'fas fa-music purple', ],
    '49': [ ' ', 'fas fa-plane purple', ],
    '4a': [ ' ', 'fas fa-square red', 'underline' ],
    '4b': [ ' ', 'fas fa-square orange', 'underline' ],
    '4c': [ ' ', 'fas fa-square yellow', 'underline' ],
    '4d': [ ' ', 'fas fa-square green', 'underline' ],
    '4e': [ ' ', 'fas fa-square blue', 'underline' ],
    '4f': [ ' ', 'fas fa-square purple', 'underline' ],
    '50': [ ' ', 'fas fa-yin-yang blue', ],
    '51': [ ' ', 'fas fa-umbrella blue', ],
    '52': [ ' ', 'fas fa-phone blue', 'small' ],
    '53': [ '⁂', 'blue', 'small' ],
    '54': [ ' ', 'fas fa-sun blue', ],
    '55': [ '✿', 'blue', ],
    '56': [ ' ', 'fas fa-cut blue', ],
    '57': [ ' ', 'fas fa-volume-up blue', ],
    '58': [ ' ', 'fas fa-music blue', ],
    '59': [ ' ', 'fas fa-plane blue', ],
    '5a': [ ' ', 'fas fa-star red', 'underline' ],
    '5b': [ ' ', 'fas fa-star orange', 'underline' ],
    '5c': [ ' ', 'fas fa-star yellow', 'underline' ],
    '5d': [ ' ', 'fas fa-star green', 'underline' ],
    '5e': [ ' ', 'fas fa-star blue', 'underline' ],
    '5f': [ ' ', 'fas fa-star purple', 'underline' ],
    '60': [ ' ', 'fas fa-yin-yang green', ],
    '61': [ ' ', 'fas fa-umbrella green', ],
    '62': [ ' ', 'fas fa-phone green', 'small' ],
    '63': [ '⁂', 'green', 'small' ],
    '64': [ ' ', 'fas fa-sun green', ],
    '65': [ '✿', 'green', ],
    '66': [ ' ', 'fas fa-cut green', ],
    '67': [ ' ', 'fas fa-volume-up green', ],
    '68': [ ' ', 'fas fa-music green', ],
    '69': [ ' ', 'fas fa-plane green', ],
    '6a': [ ' ', 'fas fa-arrow-left red', 'underline' ],
    '6b': [ ' ', 'fas fa-arrow-left orange', 'underline' ],
    '6c': [ ' ', 'fas fa-arrow-left yellow', 'underline' ],
    '6d': [ ' ', 'fas fa-arrow-left green', 'underline' ],
    '6e': [ ' ', 'fas fa-arrow-left blue', 'underline' ],
    '6f': [ ' ', 'fas fa-arrow-left purple', 'underline' ],
    '70': [ ' ', 'fas fa-yin-yang yellow', ],
    '71': [ ' ', 'fas fa-umbrella yellow', ],
    '72': [ ' ', 'fas fa-phone yellow', 'small' ],
    '73': [ '⁂', 'yellow', 'small' ],
    '74': [ ' ', 'fas fa-sun yellow', ],
    '75': [ '✿', 'yellow', ],
    '76': [ ' ', 'fas fa-cut yellow', ],
    '77': [ ' ', 'fas fa-volume-up yellow', ],
    '78': [ ' ', 'fas fa-music yellow', ],
    '79': [ ' ', 'fas fa-plane yellow', ],
    '7a': [ ' ', 'fas fa-arrow-up red', 'underline' ],
    '7b': [ ' ', 'fas fa-arrow-up orange', 'underline' ],
    '7c': [ ' ', 'fas fa-arrow-up yellow', 'underline' ],
    '7d': [ ' ', 'fas fa-arrow-up green', 'underline' ],
    '7e': [ ' ', 'fas fa-arrow-up blue', 'underline' ],
    '7f': [ ' ', 'fas fa-arrow-up purple', 'underline' ],
    '80': [ ' ', 'fas fa-yin-yang orange', ],
    '81': [ ' ', 'fas fa-umbrella orange', ],
    '82': [ ' ', 'fas fa-phone orange', 'small' ],
    '83': [ '⁂', 'orange', 'small' ],
    '84': [ ' ', 'fas fa-sun orange', ],
    '85': [ '✿', 'orange', ],
    '86': [ ' ', 'fas fa-cut orange', ],
    '87': [ ' ', 'fas fa-volume-up orange', ],
    '88': [ ' ', 'fas fa-music orange', ],
    '89': [ ' ', 'fas fa-plane orange', ],
    '8a': [ ' ', 'fas fa-arrow-right red', 'underline' ],
    '8b': [ ' ', 'fas fa-arrow-right orange', 'underline' ],
    '8c': [ ' ', 'fas fa-arrow-right yellow', 'underline' ],
    '8d': [ ' ', 'fas fa-arrow-right green', 'underline' ],
    '8e': [ ' ', 'fas fa-arrow-right blue', 'underline' ],
    '8f': [ ' ', 'fas fa-arrow-right purple', 'underline' ],
    '90': [ ' ', 'fas fa-yin-yang red', ],
    '91': [ ' ', 'fas fa-umbrella red', ],
    '92': [ ' ', 'fas fa-phone red', 'small' ],
    '93': [ '⁂', 'red', 'small' ],
    '94': [ ' ', 'fas fa-sun red', ],
    '95': [ '✿', 'red', ],
    '96': [ ' ', 'fas fa-cut red', ],
    '97': [ ' ', 'fas fa-volume-up red', ],
    '98': [ ' ', 'fas fa-music red', ],
    '99': [ ' ', 'fas fa-plane red', ],
    '9a': [ ' ', 'fas fa-arrow-down red', 'underline' ],
    '9b': [ ' ', 'fas fa-arrow-down orange', 'underline' ],
    '9c': [ ' ', 'fas fa-arrow-down yellow', 'underline' ],
    '9d': [ ' ', 'fas fa-arrow-down green', 'underline' ],
    '9e': [ ' ', 'fas fa-arrow-down blue', 'underline' ],
    '9f': [ ' ', 'fas fa-arrow-down purple', 'underline' ],
    'a0': [ ' ', 'fas fa-circle red fas fa-circle', ],
    'a1': [ ' ', 'fas fa-plus red fas fa-plus', ],
    'a2': [ ' ', 'fas fa-heart red', ],
    'a3': [ '▲', 'red', ],
    'a4': [ ' ', 'fas fa-square red', ],
    'a5': [ ' ', 'fas fa-star red', ],
    'a6': [ ' ', 'fas fa-arrow-left red', ],
    'a7': [ ' ', 'fas fa-arrow-up red', ],
    'a8': [ ' ', 'fas fa-arrow-right red', ],
    'a9': [ ' ', 'fas fa-arrow-down red', ],
    'aa': [ '①', 'red', ],
    'ab': [ '②', 'red', ],
    'ac': [ '③', 'red', ],
    'ad': [ '④', 'red', ],
    'ae': [ '⑤', 'red', ],
    'af': [ '⑥', 'red', ],
    'b0': [ ' ', 'fas fa-circle orange fas fa-circle', ],
    'b1': [ ' ', 'fas fa-plus orange fas fa-plus', ],
    'b2': [ ' ', 'fas fa-heart orange', ],
    'b3': [ '▲', 'orange', ],
    'b4': [ ' ', 'fas fa-square orange', ],
    'b5': [ ' ', 'fas fa-star orange', ],
    'b6': [ ' ', 'fas fa-arrow-left orange', ],
    'b7': [ ' ', 'fas fa-arrow-up orange', ],
    'b8': [ ' ', 'fas fa-arrow-right orange', ],
    'b9': [ ' ', 'fas fa-arrow-down orange', ],
    'ba': [ '①', 'orange', ],
    'bb': [ '②', 'orange', ],
    'bc': [ '③', 'orange', ],
    'bd': [ '④', 'orange', ],
    'be': [ '⑤', 'orange', ],
    'bf': [ '⑥', 'orange', ],
    'c0': [ ' ', 'fas fa-circle yellow fas fa-circle', ],
    'c1': [ ' ', 'fas fa-plus yellow fas fa-plus', ],
    'c2': [ ' ', 'fas fa-heart yellow', ],
    'c3': [ '▲', 'yellow', ],
    'c4': [ ' ', 'fas fa-square yellow', ],
    'c5': [ ' ', 'fas fa-star yellow', ],
    'c6': [ ' ', 'fas fa-arrow-left yellow', ],
    'c7': [ ' ', 'fas fa-arrow-up yellow', ],
    'c8': [ ' ', 'fas fa-arrow-right yellow', ],
    'c9': [ ' ', 'fas fa-arrow-down yellow', ],
    'ca': [ '①', 'yellow', ],
    'cb': [ '②', 'yellow', ],
    'cc': [ '③', 'yellow', ],
    'cd': [ '④', 'yellow', ],
    'ce': [ '⑤', 'yellow', ],
    'cf': [ '⑥', 'yellow', ],
    'd0': [ ' ', 'fas fa-circle green fas fa-circle', ],
    'd1': [ ' ', 'fas fa-plus green fas fa-plus', ],
    'd2': [ ' ', 'fas fa-heart green', ],
    'd3': [ '▲', 'green', ],
    'd4': [ ' ', 'fas fa-square green', ],
    'd5': [ ' ', 'fas fa-star green', ],
    'd6': [ ' ', 'fas fa-arrow-left green', ],
    'd7': [ ' ', 'fas fa-arrow-up green', ],
    'd8': [ ' ', 'fas fa-arrow-right green', ],
    'd9': [ ' ', 'fas fa-arrow-down green', ],
    'da': [ '①', 'green', ],
    'db': [ '②', 'green', ],
    'dc': [ '③', 'green', ],
    'dd': [ '④', 'green', ],
    'de': [ '⑤', 'green', ],
    'df': [ '⑥', 'green', ],
    'e0': [ ' ', 'fas fa-circle blue fas fa-circle', ],
    'e1': [ ' ', 'fas fa-plus blue fas fa-plus', ],
    'e2': [ ' ', 'fas fa-heart blue', ],
    'e3': [ '▲', 'blue', ],
    'e4': [ ' ', 'fas fa-square blue', ],
    'e5': [ ' ', 'fas fa-star blue', ],
    'e6': [ ' ', 'fas fa-arrow-left blue', ],
    'e7': [ ' ', 'fas fa-arrow-up blue', ],
    'e8': [ ' ', 'fas fa-arrow-right blue', ],
    'e9': [ ' ', 'fas fa-arrow-down blue', ],
    'ea': [ '①', 'blue', ],
    'eb': [ '②', 'blue', ],
    'ec': [ '③', 'blue', ],
    'ed': [ '④', 'blue', ],
    'ee': [ '⑤', 'blue', ],
    'ef': [ '⑥', 'blue', ],
    'f0': [ ' ', 'fas fa-circle purple', ],
    'f1': [ ' ', 'fas fa-plus purple fas fa-plus', ],
    'f2': [ ' ', 'fas fa-heart purple', ],
    'f3': [ '▲', 'purple', ],
    'f4': [ ' ', 'fas fa-square purple', ],
    'f5': [ ' ', 'fas fa-star purple', ],
    'f6': [ ' ', 'fas fa-arrow-left purple', ],
    'f7': [ ' ', 'fas fa-arrow-up purple', ],
    'f8': [ ' ', 'fas fa-arrow-right purple', ],
    'f9': [ ' ', 'fas fa-arrow-down purple', ],
    'fa': [ '①', 'purple', ],
    'fb': [ '②', 'purple', ],
    'fc': [ '③', 'purple', ],
    'fd': [ '④', 'purple', ],
    'fe': [ '⑤', 'purple', ],
    'ff': [ '⑥', 'purple', ],
  },
});