'use strict';

addArrayHexList({
  name: 'Geometric & Common Shapes',
  number: '209',
  comment: '2xx core encodes 6 basic colors in letters and maximizes the use of ▲■♥★',
  data: {
    '00': ['🞧', '', 'underline'],
    '01': ['●', '', 'underline'],
    '02': ['♥', '', 'underline'],
    '03': ['▲', '', 'underline'],
    '04': ['■', '', 'underline'],
    '05': ['★', '', 'underline'],
    '06': ['🡄', '', 'underline'],
    '07': ['🡅', '', 'underline'],
    '08': ['🡆', '', 'underline'],
    '09': ['🡇', '', 'underline'],
    '10': ['🞧', '', ''],
    '11': ['●', '', ''],
    '12': ['♥', '', ''],
    '13': ['▲', '', ''],
    '14': ['■', '', ''],
    '15': ['★', '', ''],
    '16': ['🡄', '', ''],
    '17': ['🡅', '', ''],
    '18': ['🡆', '', ''],
    '19': ['🡇', '', ''],
    '20': ['🞧', 'gray', ''],
    '21': ['●', 'gray', ''],
    '22': ['♥', 'gray', ''],
    '23': ['▲', 'gray', ''],
    '24': ['■', 'gray', ''],
    '25': ['★', 'gray', ''],
    '26': ['🡄', 'gray', ''],
    '27': ['🡅', 'gray', ''],
    '28': ['🡆', 'gray', ''],
    '29': ['🡇', 'gray', ''],
    '30': ['🞧', 'white', ''],
    '31': ['●', 'white', ''],
    '32': ['♥', 'white', ''],
    '33': ['▲', 'white', ''],
    '34': ['■', 'white', ''],
    '35': ['★', 'white', ''],
    '36': ['🡄', 'white', ''],
    '37': ['🡅', 'white', ''],
    '38': ['🡆', 'white', ''],
    '39': ['🡇', 'white', ''],
    '40': ['☯', 'purple', ''],
    '41': ['☂', 'purple', ''],
    '42': ['🕿', 'purple', 'small'],
    '43': ['⁂', 'purple', 'small'],
    '44': ['☀', 'purple', ''],
    '45': ['✿', 'purple', ''],
    '46': ['✂', 'purple', ''],
    '47': ['🕪', 'purple', ''],
    '48': ['🕶', 'purple', ''],
    '49': ['🛧', 'purple', ''],
    '50': ['☯', 'blue', ''],
    '51': ['☂', 'blue', ''],
    '52': ['🕿', 'blue', 'small'],
    '53': ['⁂', 'blue', 'small'],
    '54': ['☀', 'blue', ''],
    '55': ['✿', 'blue', ''],
    '56': ['✂', 'blue', ''],
    '57': ['🕪', 'blue', ''],
    '58': ['🕶', 'blue', ''],
    '59': ['🛧', 'blue', ''],
    '60': ['☯', 'green', ''],
    '61': ['☂', 'green', ''],
    '62': ['🕿', 'green', 'small'],
    '63': ['⁂', 'green', 'small'],
    '64': ['☀', 'green', ''],
    '65': ['✿', 'green', ''],
    '66': ['✂', 'green', ''],
    '67': ['🕪', 'green', ''],
    '68': ['🕶', 'green', ''],
    '69': ['🛧', 'green', ''],
    '70': ['☯', 'yellow', ''],
    '71': ['☂', 'yellow', ''],
    '72': ['🕿', 'yellow', 'small'],
    '73': ['⁂', 'yellow', 'small'],
    '74': ['☀', 'yellow', ''],
    '75': ['✿', 'yellow', ''],
    '76': ['✂', 'yellow', ''],
    '77': ['🕪', 'yellow', ''],
    '78': ['🕶', 'yellow', ''],
    '79': ['🛧', 'yellow', ''],
    '80': ['☯', 'orange', ''],
    '81': ['☂', 'orange', ''],
    '82': ['🕿', 'orange', 'small'],
    '83': ['⁂', 'orange', 'small'],
    '84': ['☀', 'orange', ''],
    '85': ['✿', 'orange', ''],
    '86': ['✂', 'orange', ''],
    '87': ['🕪', 'orange', ''],
    '88': ['🕶', 'orange', ''],
    '89': ['🛧', 'orange', ''],
    '90': ['☯', 'red', ''],
    '91': ['☂', 'red', ''],
    '92': ['🕿', 'red', 'small'],
    '93': ['⁂', 'red', 'small'],
    '94': ['☀', 'red', ''],
    '95': ['✿', 'red', ''],
    '96': ['✂', 'red', ''],
    '97': ['🕪', 'red', ''],
    '98': ['🕶', 'red', ''],
    '99': ['🛧', 'red', ''],
    '0A': ['🞧', 'red', ''],
    '0B': ['🞧', 'orange', 'underline'],
    '0C': ['🞧', 'yellow', 'underline'],
    '0D': ['🞧', 'green', 'underline'],
    '0E': ['🞧', 'blue', 'underline'],
    '0F': ['🞧', 'purple', 'underline'],
    '1A': ['●', 'red', 'underline'],
    '1B': ['●', 'orange', 'underline'],
    '1C': ['●', 'yellow', 'underline'],
    '1D': ['●', 'green', 'underline'],
    '1E': ['●', 'blue', 'underline'],
    '1F': ['●', 'purple', 'underline'],
    '2A': ['♥', 'red', 'underline'],
    '2B': ['♥', 'orange', 'underline'],
    '2C': ['♥', 'yellow', 'underline'],
    '2D': ['♥', 'green', 'underline'],
    '2E': ['♥', 'blue', 'underline'],
    '2F': ['♥', 'purple', 'underline'],
    '3A': ['▲', 'red', 'underline'],
    '3B': ['▲', 'orange', 'underline'],
    '3C': ['▲', 'yellow', 'underline'],
    '3D': ['▲', 'green', 'underline'],
    '3E': ['▲', 'blue', 'underline'],
    '3F': ['▲', 'purple', 'underline'],
    '4A': ['■', 'red', 'underline'],
    '4B': ['■', 'orange', 'underline'],
    '4C': ['■', 'yellow', 'underline'],
    '4D': ['■', 'green', 'underline'],
    '4E': ['■', 'blue', 'underline'],
    '4F': ['■', 'purple', 'underline'],
    '5A': ['★', 'red', 'underline'],
    '5B': ['★', 'orange', 'underline'],
    '5C': ['★', 'yellow', 'underline'],
    '5D': ['★', 'green', 'underline'],
    '5E': ['★', 'blue', 'underline'],
    '5F': ['★', 'purple', 'underline'],
    '6A': ['🡄', 'red', 'underline'],
    '6B': ['🡄', 'orange', 'underline'],
    '6C': ['🡄', 'yellow', 'underline'],
    '6D': ['🡄', 'green', 'underline'],
    '6E': ['🡄', 'blue', 'underline'],
    '6F': ['🡄', 'purple', 'underline'],
    '7A': ['🡅', 'red', 'underline'],
    '7B': ['🡅', 'orange', 'underline'],
    '7C': ['🡅', 'yellow', 'underline'],
    '7D': ['🡅', 'green', 'underline'],
    '7E': ['🡅', 'blue', 'underline'],
    '7F': ['🡅', 'purple', 'underline'],
    '8A': ['🡆', 'red', 'underline'],
    '8B': ['🡆', 'orange', 'underline'],
    '8C': ['🡆', 'yellow', 'underline'],
    '8D': ['🡆', 'green', 'underline'],
    '8E': ['🡆', 'blue', 'underline'],
    '8F': ['🡆', 'purple', 'underline'],
    '9A': ['🡇', 'red', 'underline'],
    '9B': ['🡇', 'orange', 'underline'],
    '9C': ['🡇', 'yellow', 'underline'],
    '9D': ['🡇', 'green', 'underline'],
    '9E': ['🡇', 'blue', 'underline'],
    '9F': ['🡇', 'purple', 'underline'],
    'A0': ['🞧', 'red', ''],
    'A1': ['●', 'red', ''],
    'A2': ['♥', 'red', ''],
    'A3': ['▲', 'red', ''],
    'A4': ['■', 'red', ''],
    'A5': ['★', 'red', ''],
    'A6': ['🡄', 'red', ''],
    'A7': ['🡅', 'red', ''],
    'A8': ['🡆', 'red', ''],
    'A9': ['🡇', 'red', ''],
    'AA': ['①', 'red', ''],
    'AB': ['②', 'red', ''],
    'AC': ['③', 'red', ''],
    'AD': ['④', 'red', ''],
    'AE': ['⑤', 'red', ''],
    'AF': ['⑥', 'red', ''],
    'B0': ['🞧', 'orange', ''],
    'B1': ['●', 'orange', ''],
    'B2': ['♥', 'orange', ''],
    'B3': ['▲', 'orange', ''],
    'B4': ['■', 'orange', ''],
    'B5': ['★', 'orange', ''],
    'B6': ['🡄', 'orange', ''],
    'B7': ['🡅', 'orange', ''],
    'B8': ['🡆', 'orange', ''],
    'B9': ['🡇', 'orange', ''],
    'BA': ['①', 'orange', ''],
    'BB': ['②', 'orange', ''],
    'BC': ['③', 'orange', ''],
    'BD': ['④', 'orange', ''],
    'BE': ['⑤', 'orange', ''],
    'BF': ['⑥', 'orange', ''],
    'C0': ['🞧', 'yellow', ''],
    'C1': ['●', 'yellow', ''],
    'C2': ['♥', 'yellow', ''],
    'C3': ['▲', 'yellow', ''],
    'C4': ['■', 'yellow', ''],
    'C5': ['★', 'yellow', ''],
    'C6': ['🡄', 'yellow', ''],
    'C7': ['🡅', 'yellow', ''],
    'C8': ['🡆', 'yellow', ''],
    'C9': ['🡇', 'yellow', ''],
    'CA': ['①', 'yellow', ''],
    'CB': ['②', 'yellow', ''],
    'CC': ['③', 'yellow', ''],
    'CD': ['④', 'yellow', ''],
    'CE': ['⑤', 'yellow', ''],
    'CF': ['⑥', 'yellow', ''],
    'D0': ['🞧', 'yellow', ''],
    'D1': ['●', 'green', ''],
    'D2': ['♥', 'green', ''],
    'D3': ['▲', 'green', ''],
    'D4': ['■', 'green', ''],
    'D5': ['★', 'green', ''],
    'D6': ['🡄', 'green', ''],
    'D7': ['🡅', 'green', ''],
    'D8': ['🡆', 'green', ''],
    'D9': ['🡇', 'green', ''],
    'DA': ['①', 'green', ''],
    'DB': ['②', 'green', ''],
    'DC': ['③', 'green', ''],
    'DD': ['④', 'green', ''],
    'DE': ['⑤', 'green', ''],
    'DF': ['⑥', 'green', ''],
    'E0': ['🞧', 'blue', ''],
    'E1': ['●', 'blue', ''],
    'E2': ['♥', 'blue', ''],
    'E3': ['▲', 'blue', ''],
    'E4': ['■', 'blue', ''],
    'E5': ['★', 'blue', ''],
    'E6': ['🡄', 'blue', ''],
    'E7': ['🡅', 'blue', ''],
    'E8': ['🡆', 'blue', ''],
    'E9': ['🡇', 'blue', ''],
    'EA': ['①', 'blue', ''],
    'EB': ['②', 'blue', ''],
    'EC': ['③', 'blue', ''],
    'ED': ['④', 'blue', ''],
    'EE': ['⑤', 'blue', ''],
    'EF': ['⑥', 'blue', ''],
    'F0': ['🞧', 'purple', ''],
    'F1': ['●', 'purple', ''],
    'F2': ['♥', 'purple', ''],
    'F3': ['▲', 'purple', ''],
    'F4': ['■', 'purple', ''],
    'F5': ['★', 'purple', ''],
    'F6': ['🡄', 'purple', ''],
    'F7': ['🡅', 'purple', ''],
    'F8': ['🡆', 'purple', ''],
    'F9': ['🡇', 'purple', ''],
    'FA': ['①', 'purple', ''],
    'FB': ['②', 'purple', ''],
    'FC': ['③', 'purple', ''],
    'FD': ['④', 'purple', ''],
    'FE': ['⑤', 'purple', ''],
    'FF': ['⑥', 'purple', ''],
  },
});
