// exported at 9/23/2018, 7:27:21 PM
'use strict';

addArrayHexList({
  name: 'ASCII & Frequency',
  author: 'Hus',
  comment: '3xx (ASCII Optimiezed + Letter Frequency) use 26 distinguishable char (no color/black) to encode lower case & white to encode upper case..',
  number: '301',
  data: {
    '00': [ '🞧', , 'underline' ],
    '01': [ '●', , 'underline' ],
    '02': [ '♥', , 'underline' ],
    '03': [ '▲', , 'underline' ],
    '04': [ '■', , 'underline' ],
    '05': [ '★', , 'underline' ],
    '06': [ '🡄', , 'underline' ],
    '07': [ '🡅', , 'underline' ],
    '08': [ '🡆', , 'underline' ],
    '09': [ '🡇', , 'underline' ],
    '0a': [ '●', 'red', ],
    '0b': [ '●', 'orange', 'underline' ],
    '0c': [ '●', 'yellow', 'underline' ],
    '0d': [ '●', 'green', 'underline' ],
    '0e': [ '●', 'black', 'underline' ],
    '0f': [ '●', 'purple', 'underline' ],
    '10': [ '🞧', , ],
    '11': [ '●', , ],
    '12': [ '♥', , ],
    '13': [ '▲', , ],
    '14': [ '■', , ],
    '15': [ '★', , ],
    '16': [ '🡄', , ],
    '17': [ '🡅', , ],
    '18': [ '🡆', , ],
    '19': [ '🡇', , ],
    '1a': [ '🞧', 'red', 'underline' ],
    '1b': [ '🞧', 'orange', 'underline' ],
    '1c': [ '🞧', 'yellow', 'underline' ],
    '1d': [ '🞧', 'green', 'underline' ],
    '1e': [ '🞧', 'black', 'underline' ],
    '1f': [ '🞧', 'purple', 'underline' ],
    '20': [ '🞧', 'gray', ],
    '21': [ '●', 'gray', ],
    '22': [ '♥', 'gray', ],
    '23': [ '▲', 'gray', ],
    '24': [ '■', 'gray', ],
    '25': [ '★', 'gray', ],
    '26': [ '🡄', 'gray', ],
    '27': [ '🡅', 'gray', ],
    '28': [ '🡆', 'gray', ],
    '29': [ '🡇', 'gray', ],
    '2a': [ '♥', 'red', 'underline' ],
    '2b': [ '♥', 'orange', 'underline' ],
    '2c': [ '♥', 'yellow', 'underline' ],
    '2d': [ '♥', 'green', 'underline' ],
    '2e': [ '♥', 'black', 'underline' ],
    '2f': [ '♥', 'purple', 'underline' ],
    '30': [ '🄌', 'k', ],
    '31': [ '➊', 'k', ],
    '32': [ '➋', 'k', ],
    '33': [ '➌', 'k', ],
    '34': [ '➍', 'k', ],
    '35': [ '➎', 'k', ],
    '36': [ '➏', 'k', ],
    '37': [ '➐', 'k', ],
    '38': [ '➑', 'k', ],
    '39': [ '➒', 'k', ],
    '3a': [ '▲', 'red', 'underline' ],
    '3b': [ '▲', 'orange', 'underline' ],
    '3c': [ '▲', 'yellow', 'underline' ],
    '3d': [ '▲', 'green', 'underline' ],
    '3e': [ '▲', 'black', 'underline' ],
    '3f': [ '▲', 'purple', 'underline' ],
    '40': [ '☯', 'purple', ],
    '41': [ '▲', 'white', ],
    '42': [ '♬', 'white', ],
    '43': [ '🛧', 'white', ],
    '44': [ '🡇', 'white', ],
    '45': [ '★', 'white', ],
    '46': [ '🕿', 'white', ],
    '47': [ '⁂', 'white', ],
    '48': [ '🡅', 'white', ],
    '49': [ '⬤', 'white', ],
    '4a': [ '🕭', 'white', ],
    '4b': [ '👁', 'white', ],
    '4c': [ '✂', 'white', ],
    '4d': [ '☀', 'white', ],
    '4e': [ '🞧', 'white', ],
    '4f': [ '■', 'white', ],
    '50': [ '🕪', 'white', ],
    '51': [ '♛', 'white', ],
    '52': [ '🡆', 'white', ],
    '53': [ '🡄', 'white', ],
    '54': [ '♥', 'white', ],
    '55': [ '☂', 'white', ],
    '56': [ '♻', 'white', ],
    '57': [ '☯', 'white', ],
    '58': [ '🕷', 'white', ],
    '59': [ '✿', 'white', ],
    '5a': [ '⏲', 'white', ],
    '5b': [ '★', 'orange', 'underline' ],
    '5c': [ '★', 'yellow', 'underline' ],
    '5d': [ '★', 'green', 'underline' ],
    '5e': [ '★', 'black', 'underline' ],
    '5f': [ '★', 'purple', 'underline' ],
    '60': [ '☯', 'green', ],
    '61': [ '▲', 'k', ],
    '62': [ '♬', 'k', ],
    '63': [ '🛧', 'k', ],
    '64': [ '🡇', 'k', ],
    '65': [ '★', 'k', ],
    '66': [ '🕿', 'k', ],
    '67': [ '⁂', 'k', ],
    '68': [ '🡅', 'k', ],
    '69': [ '⬤', 'k', ],
    '6a': [ '🕭', 'k', ],
    '6b': [ '👁', 'k', ],
    '6c': [ '✂', 'k', ],
    '6d': [ '☀', 'k', ],
    '6e': [ '🞧', 'k', ],
    '6f': [ '■', 'k', ],
    '70': [ '🕪', 'k', ],
    '71': [ '♛', 'k', ],
    '72': [ '🡆', 'k', ],
    '73': [ '🡄', 'k', ],
    '74': [ '♥', 'k', ],
    '75': [ '☂', 'k', ],
    '76': [ '♻', 'k', ],
    '77': [ '☯', 'k', ],
    '78': [ '🕷', 'k', ],
    '79': [ '✿', 'k', ],
    '7a': [ '⏲', 'k', ],
    '7b': [ '🡅', 'orange', 'underline' ],
    '7c': [ '🡅', 'yellow', 'underline' ],
    '7d': [ '🡅', 'green', 'underline' ],
    '7e': [ '🡅', 'black', 'underline' ],
    '7f': [ '🡅', 'purple', 'underline' ],
    '80': [ '☯', 'orange', ],
    '81': [ '☂', 'orange', ],
    '82': [ '🕿', 'orange', 'small' ],
    '83': [ '⁂', 'orange', 'small' ],
    '84': [ '☀', 'orange', ],
    '85': [ '✿', 'orange', ],
    '86': [ '✂', 'orange', ],
    '87': [ '🕪', 'orange', ],
    '88': [ '♬', 'orange', ],
    '89': [ '🛧', 'orange', ],
    '8a': [ '🡆', 'red', 'underline' ],
    '8b': [ '🡆', 'orange', 'underline' ],
    '8c': [ '🡆', 'yellow', 'underline' ],
    '8d': [ '🡆', 'green', 'underline' ],
    '8e': [ '🡆', 'black', 'underline' ],
    '8f': [ '🡆', 'purple', 'underline' ],
    '90': [ '☯', 'red', ],
    '91': [ '☂', 'red', ],
    '92': [ '🕿', 'red', 'small' ],
    '93': [ '⁂', 'red', 'small' ],
    '94': [ '☀', 'red', ],
    '95': [ '✿', 'red', ],
    '96': [ '✂', 'red', ],
    '97': [ '🕪', 'red', ],
    '98': [ '♬', 'red', ],
    '99': [ '🛧', 'red', ],
    '9a': [ '🡇', 'red', 'underline' ],
    '9b': [ '🡇', 'orange', 'underline' ],
    '9c': [ '🡇', 'yellow', 'underline' ],
    '9d': [ '🡇', 'green', 'underline' ],
    '9e': [ '🡇', 'black', 'underline' ],
    '9f': [ '🡇', 'purple', 'underline' ],
    'a0': [ '●', 'red', ],
    'a1': [ '🞧', 'red', ],
    'a2': [ '♥', 'red', ],
    'a3': [ '▲', 'red', ],
    'a4': [ '■', 'red', ],
    'a5': [ '★', 'red', ],
    'a6': [ '🡄', 'red', ],
    'a7': [ '🡅', 'red', ],
    'a8': [ '🡆', 'red', ],
    'a9': [ '🡇', 'red', ],
    'aa': [ '①', 'red', ],
    'ab': [ '②', 'red', ],
    'ac': [ '③', 'red', ],
    'ad': [ '④', 'red', ],
    'ae': [ '⑤', 'red', ],
    'af': [ '⑥', 'red', ],
    'b0': [ '●', 'orange', ],
    'b1': [ '🞧', 'orange', ],
    'b2': [ '♥', 'orange', ],
    'b3': [ '▲', 'orange', ],
    'b4': [ '■', 'orange', ],
    'b5': [ '★', 'orange', ],
    'b6': [ '🡄', 'orange', ],
    'b7': [ '🡅', 'orange', ],
    'b8': [ '🡆', 'orange', ],
    'b9': [ '🡇', 'orange', ],
    'ba': [ '①', 'orange', ],
    'bb': [ '②', 'orange', ],
    'bc': [ '③', 'orange', ],
    'bd': [ '④', 'orange', ],
    'be': [ '⑤', 'orange', ],
    'bf': [ '⑥', 'orange', ],
    'c0': [ '●', 'yellow', ],
    'c1': [ '🞧', 'yellow', ],
    'c2': [ '♥', 'yellow', ],
    'c3': [ '▲', 'yellow', ],
    'c4': [ '■', 'yellow', ],
    'c5': [ '★', 'yellow', ],
    'c6': [ '🡄', 'yellow', ],
    'c7': [ '🡅', 'yellow', ],
    'c8': [ '🡆', 'yellow', ],
    'c9': [ '🡇', 'yellow', ],
    'ca': [ '①', 'yellow', ],
    'cb': [ '②', 'yellow', ],
    'cc': [ '③', 'yellow', ],
    'cd': [ '④', 'yellow', ],
    'ce': [ '⑤', 'yellow', ],
    'cf': [ '⑥', 'yellow', ],
    'd0': [ '●', 'yellow', ],
    'd1': [ '🞧', 'green', ],
    'd2': [ '♥', 'green', ],
    'd3': [ '▲', 'green', ],
    'd4': [ '■', 'green', ],
    'd5': [ '★', 'green', ],
    'd6': [ '🡄', 'green', ],
    'd7': [ '🡅', 'green', ],
    'd8': [ '🡆', 'green', ],
    'd9': [ '🡇', 'green', ],
    'da': [ '①', 'green', ],
    'db': [ '②', 'green', ],
    'dc': [ '③', 'green', ],
    'dd': [ '④', 'green', ],
    'de': [ '⑤', 'green', ],
    'df': [ '⑥', 'green', ],
    'e0': [ '●', 'black', ],
    'e1': [ '🞧', 'black', ],
    'e2': [ '♥', 'black', ],
    'e3': [ '▲', 'black', ],
    'e4': [ '■', 'black', ],
    'e5': [ '★', 'black', ],
    'e6': [ '🡄', 'black', ],
    'e7': [ '🡅', 'black', ],
    'e8': [ '🡆', 'black', ],
    'e9': [ '🡇', 'black', ],
    'ea': [ '①', 'black', ],
    'eb': [ '②', 'black', ],
    'ec': [ '③', 'black', ],
    'ed': [ '④', 'black', ],
    'ee': [ '⑤', 'black', ],
    'ef': [ '⑥', 'black', ],
    'f0': [ '●', 'purple', ],
    'f1': [ '🞧', 'purple', ],
    'f2': [ '♥', 'purple', ],
    'f3': [ '▲', 'purple', ],
    'f4': [ '■', 'purple', ],
    'f5': [ '★', 'purple', ],
    'f6': [ '🡄', 'purple', ],
    'f7': [ '🡅', 'purple', ],
    'f8': [ '🡆', 'purple', ],
    'f9': [ '🡇', 'purple', ],
    'fa': [ '①', 'purple', ],
    'fb': [ '②', 'purple', ],
    'fc': [ '③', 'purple', ],
    'fd': [ '④', 'purple', ],
    'fe': [ '⑤', 'purple', ],
    'ff': [ '⑥', 'purple', ],
  },
});