// exported at 9/23/2018, 7:26:37 PM
'use strict';

addArrayHexList({
  name: 'Geometric & Common Shapes',
  author: 'Hus',
  comment: '2xx core encodes 6 basic colors in letters and maximizes the use of ⬤▲■♥★',
  number: '212',
  data: {
    '00': [ '🞧', 'black', 'underline' ],
    '01': [ '⬤', 'black', 'underline' ],
    '02': [ '♥', 'black', 'underline' ],
    '03': [ '▲', 'black', 'underline' ],
    '04': [ '■', 'black', 'underline' ],
    '05': [ '★', 'black', 'underline' ],
    '06': [ '🡄', 'black', 'underline' ],
    '07': [ '🡅', 'black', 'underline' ],
    '08': [ '🡆', 'black', 'underline' ],
    '09': [ '🡇', 'black', 'underline' ],
    '0a': [ '⬤', 'red', 'underline' ],
    '0b': [ '⬤', 'orange', 'underline' ],
    '0c': [ '⬤', 'yellow', 'underline' ],
    '0d': [ '⬤', 'green', 'underline' ],
    '0e': [ '⬤', 'blue', 'underline' ],
    '0f': [ '⬤', 'purple', 'underline' ],
    '10': [ '🞧', 'black', ],
    '11': [ '⬤', 'black', ],
    '12': [ '♥', 'black', ],
    '13': [ '▲', 'black', ],
    '14': [ '■', 'black', ],
    '15': [ '★', 'black', ],
    '16': [ '🡄', 'black', ],
    '17': [ '🡅', 'black', ],
    '18': [ '🡆', 'black', ],
    '19': [ '🡇', 'black', ],
    '1a': [ '🞧', 'red', 'underline' ],
    '1b': [ '🞧', 'orange', 'underline' ],
    '1c': [ '🞧', 'yellow', 'underline' ],
    '1d': [ '🞧', 'green', 'underline' ],
    '1e': [ '🞧', 'blue', 'underline' ],
    '1f': [ '🞧', 'purple', 'underline' ],
    '20': [ '🞧', 'gray', ],
    '21': [ '⬤', 'gray', ],
    '22': [ '♥', 'gray', ],
    '23': [ '▲', 'gray', ],
    '24': [ '■', 'gray', ],
    '25': [ '★', 'gray', ],
    '26': [ '🡄', 'gray', ],
    '27': [ '🡅', 'gray', ],
    '28': [ '🡆', 'gray', ],
    '29': [ '🡇', 'gray', ],
    '2a': [ '♥', 'red', 'underline' ],
    '2b': [ '♥', 'orange', 'underline' ],
    '2c': [ '♥', 'yellow', 'underline' ],
    '2d': [ '♥', 'green', 'underline' ],
    '2e': [ '♥', 'blue', 'underline' ],
    '2f': [ '♥', 'purple', 'underline' ],
    '30': [ '🞧', 'white', ],
    '31': [ '⬤', 'white', ],
    '32': [ '♥', 'white', ],
    '33': [ '▲', 'white', ],
    '34': [ '■', 'white', ],
    '35': [ '★', 'white', ],
    '36': [ '🡄', 'white', ],
    '37': [ '🡅', 'white', ],
    '38': [ '🡆', 'white', ],
    '39': [ '🡇', 'white', ],
    '3a': [ '▲', 'red', 'underline' ],
    '3b': [ '▲', 'orange', 'underline' ],
    '3c': [ '▲', 'yellow', 'underline' ],
    '3d': [ '▲', 'green', 'underline' ],
    '3e': [ '▲', 'blue', 'underline' ],
    '3f': [ '▲', 'purple', 'underline' ],
    '40': [ '☯', 'purple', ],
    '41': [ '☂', 'purple', ],
    '42': [ '🕿', 'purple', 'small' ],
    '43': [ '⁂', 'purple', 'small' ],
    '44': [ '☀', 'purple', ],
    '45': [ '✿', 'purple', ],
    '46': [ '✂', 'purple', ],
    '47': [ '🕪', 'purple', ],
    '48': [ '♬', 'purple', ],
    '49': [ '🛧', 'purple', ],
    '4a': [ '■', 'red', 'underline' ],
    '4b': [ '■', 'orange', 'underline' ],
    '4c': [ '■', 'yellow', 'underline' ],
    '4d': [ '■', 'green', 'underline' ],
    '4e': [ '■', 'blue', 'underline' ],
    '4f': [ '■', 'purple', 'underline' ],
    '50': [ '☯', 'blue', ],
    '51': [ '☂', 'blue', ],
    '52': [ '🕿', 'blue', 'small' ],
    '53': [ '⁂', 'blue', 'small' ],
    '54': [ '☀', 'blue', ],
    '55': [ '✿', 'blue', ],
    '56': [ '✂', 'blue', ],
    '57': [ '🕪', 'blue', ],
    '58': [ '♬', 'blue', ],
    '59': [ '🛧', 'blue', ],
    '5a': [ '★', 'red', 'underline' ],
    '5b': [ '★', 'orange', 'underline' ],
    '5c': [ '★', 'yellow', 'underline' ],
    '5d': [ '★', 'green', 'underline' ],
    '5e': [ '★', 'blue', 'underline' ],
    '5f': [ '★', 'purple', 'underline' ],
    '60': [ '☯', 'green', ],
    '61': [ '☂', 'green', ],
    '62': [ '🕿', 'green', 'small' ],
    '63': [ '⁂', 'green', 'small' ],
    '64': [ '☀', 'green', ],
    '65': [ '✿', 'green', ],
    '66': [ '✂', 'green', ],
    '67': [ '🕪', 'green', ],
    '68': [ '♬', 'green', ],
    '69': [ '🛧', 'green', ],
    '6a': [ '🡄', 'red', 'underline' ],
    '6b': [ '🡄', 'orange', 'underline' ],
    '6c': [ '🡄', 'yellow', 'underline' ],
    '6d': [ '🡄', 'green', 'underline' ],
    '6e': [ '🡄', 'blue', 'underline' ],
    '6f': [ '🡄', 'purple', 'underline' ],
    '70': [ '☯', 'yellow', ],
    '71': [ '☂', 'yellow', ],
    '72': [ '🕿', 'yellow', 'small' ],
    '73': [ '⁂', 'yellow', 'small' ],
    '74': [ '☀', 'yellow', ],
    '75': [ '✿', 'yellow', ],
    '76': [ '✂', 'yellow', ],
    '77': [ '🕪', 'yellow', ],
    '78': [ '♬', 'yellow', ],
    '79': [ '🛧', 'yellow', ],
    '7a': [ '🡅', 'red', 'underline' ],
    '7b': [ '🡅', 'orange', 'underline' ],
    '7c': [ '🡅', 'yellow', 'underline' ],
    '7d': [ '🡅', 'green', 'underline' ],
    '7e': [ '🡅', 'blue', 'underline' ],
    '7f': [ '🡅', 'purple', 'underline' ],
    '80': [ '☯', 'orange', ],
    '81': [ '☂', 'orange', ],
    '82': [ '🕿', 'orange', 'small' ],
    '83': [ '⁂', 'orange', 'small' ],
    '84': [ '☀', 'orange', ],
    '85': [ '✿', 'orange', ],
    '86': [ '✂', 'orange', ],
    '87': [ '🕪', 'orange', ],
    '88': [ '♬', 'orange', ],
    '89': [ '🛧', 'orange', ],
    '8a': [ '🡆', 'red', 'underline' ],
    '8b': [ '🡆', 'orange', 'underline' ],
    '8c': [ '🡆', 'yellow', 'underline' ],
    '8d': [ '🡆', 'green', 'underline' ],
    '8e': [ '🡆', 'blue', 'underline' ],
    '8f': [ '🡆', 'purple', 'underline' ],
    '90': [ '☯', 'red', ],
    '91': [ '☂', 'red', ],
    '92': [ '🕿', 'red', 'small' ],
    '93': [ '⁂', 'red', 'small' ],
    '94': [ '☀', 'red', ],
    '95': [ '✿', 'red', ],
    '96': [ '✂', 'red', ],
    '97': [ '🕪', 'red', ],
    '98': [ '♬', 'red', ],
    '99': [ '🛧', 'red', ],
    '9a': [ '🡇', 'red', 'underline' ],
    '9b': [ '🡇', 'orange', 'underline' ],
    '9c': [ '🡇', 'yellow', 'underline' ],
    '9d': [ '🡇', 'green', 'underline' ],
    '9e': [ '🡇', 'blue', 'underline' ],
    '9f': [ '🡇', 'purple', 'underline' ],
    'a0': [ '⬤', 'red', ],
    'a1': [ '🞧', 'red', ],
    'a2': [ '♥', 'red', ],
    'a3': [ '▲', 'red', ],
    'a4': [ '■', 'red', ],
    'a5': [ '★', 'red', ],
    'a6': [ '🡄', 'red', ],
    'a7': [ '🡅', 'red', ],
    'a8': [ '🡆', 'red', ],
    'a9': [ '🡇', 'red', ],
    'aa': [ '①', 'red', ],
    'ab': [ '②', 'red', ],
    'ac': [ '③', 'red', ],
    'ad': [ '④', 'red', ],
    'ae': [ '⑤', 'red', ],
    'af': [ '⑥', 'red', ],
    'b0': [ '⬤', 'orange', ],
    'b1': [ '🞧', 'orange', ],
    'b2': [ '♥', 'orange', ],
    'b3': [ '▲', 'orange', ],
    'b4': [ '■', 'orange', ],
    'b5': [ '★', 'orange', ],
    'b6': [ '🡄', 'orange', ],
    'b7': [ '🡅', 'orange', ],
    'b8': [ '🡆', 'orange', ],
    'b9': [ '🡇', 'orange', ],
    'ba': [ '①', 'orange', ],
    'bb': [ '②', 'orange', ],
    'bc': [ '③', 'orange', ],
    'bd': [ '④', 'orange', ],
    'be': [ '⑤', 'orange', ],
    'bf': [ '⑥', 'orange', ],
    'c0': [ '⬤', 'yellow', ],
    'c1': [ '🞧', 'yellow', ],
    'c2': [ '♥', 'yellow', ],
    'c3': [ '▲', 'yellow', ],
    'c4': [ '■', 'yellow', ],
    'c5': [ '★', 'yellow', ],
    'c6': [ '🡄', 'yellow', ],
    'c7': [ '🡅', 'yellow', ],
    'c8': [ '🡆', 'yellow', ],
    'c9': [ '🡇', 'yellow', ],
    'ca': [ '①', 'yellow', ],
    'cb': [ '②', 'yellow', ],
    'cc': [ '③', 'yellow', ],
    'cd': [ '④', 'yellow', ],
    'ce': [ '⑤', 'yellow', ],
    'cf': [ '⑥', 'yellow', ],
    'd0': [ '⬤', 'yellow', ],
    'd1': [ '🞧', 'green', ],
    'd2': [ '♥', 'green', ],
    'd3': [ '▲', 'green', ],
    'd4': [ '■', 'green', ],
    'd5': [ '★', 'green', ],
    'd6': [ '🡄', 'green', ],
    'd7': [ '🡅', 'green', ],
    'd8': [ '🡆', 'green', ],
    'd9': [ '🡇', 'green', ],
    'da': [ '①', 'green', ],
    'db': [ '②', 'green', ],
    'dc': [ '③', 'green', ],
    'dd': [ '④', 'green', ],
    'de': [ '⑤', 'green', ],
    'df': [ '⑥', 'green', ],
    'e0': [ '⬤', 'blue', ],
    'e1': [ '🞧', 'blue', ],
    'e2': [ '♥', 'blue', ],
    'e3': [ '▲', 'blue', ],
    'e4': [ '■', 'blue', ],
    'e5': [ '★', 'blue', ],
    'e6': [ '🡄', 'blue', ],
    'e7': [ '🡅', 'blue', ],
    'e8': [ '🡆', 'blue', ],
    'e9': [ '🡇', 'blue', ],
    'ea': [ '①', 'blue', ],
    'eb': [ '②', 'blue', ],
    'ec': [ '③', 'blue', ],
    'ed': [ '④', 'blue', ],
    'ee': [ '⑤', 'blue', ],
    'ef': [ '⑥', 'blue', ],
    'f0': [ '⬤', 'purple', ],
    'f1': [ '🞧', 'purple', ],
    'f2': [ '♥', 'purple', ],
    'f3': [ '▲', 'purple', ],
    'f4': [ '■', 'purple', ],
    'f5': [ '★', 'purple', ],
    'f6': [ '🡄', 'purple', ],
    'f7': [ '🡅', 'purple', ],
    'f8': [ '🡆', 'purple', ],
    'f9': [ '🡇', 'purple', ],
    'fa': [ '①', 'purple', ],
    'fb': [ '②', 'purple', ],
    'fc': [ '③', 'purple', ],
    'fd': [ '④', 'purple', ],
    'fe': [ '⑤', 'purple', ],
    'ff': [ '⑥', 'purple', ],
  },
});