// exported at 9/25/2018, 11:59:33 PM
'use strict';

addArrayHexList({
  name: 'Geometric & Common Shapes',
  author: 'Hus',
  comment: 'Strips (Colorblind-friendly) + Fontawesome of 225',
  number: '225B',
  data: {
    '00': [ ' ', 'fas fa-plus black-strips', 'underline' ],
    '01': [ ' ', 'fas fa-circle black-strips', 'underline' ],
    '02': [ ' ', 'fas fa-heart black-strips', 'underline' ],
    '03': [ '▲', 'fas fa-triangle black-strips', 'underline' ],
    '04': [ ' ', 'fas fa-square black-strips', 'underline' ],
    '05': [ ' ', 'fas fa-star black-strips', 'underline' ],
    '06': [ ' ', 'fas fa-arrow-left black-strips', 'underline' ],
    '07': [ ' ', 'fas fa-arrow-up black-strips', 'underline' ],
    '08': [ ' ', 'fas fa-arrow-right black-strips', 'underline' ],
    '09': [ ' ', 'fas fa-arrow-down black-strips', 'underline' ],
    '0a': [ ' ', 'fas fa-circle red-strips', 'underline' ],
    '0b': [ ' ', 'fas fa-circle orange-strips', 'underline' ],
    '0c': [ ' ', 'fas fa-circle yellow-strips', 'underline' ],
    '0d': [ ' ', 'fas fa-circle green-strips', 'underline' ],
    '0e': [ ' ', 'fas fa-circle blue-strips', 'underline' ],
    '0f': [ ' ', 'fas fa-circle purple-strips', 'underline' ],
    '10': [ ' ', 'fas fa-plus black-strips', ],
    '11': [ ' ', 'fas fa-circle black-strips', ],
    '12': [ ' ', 'fas fa-heart black-strips', ],
    '13': [ '▲', 'black-strips', ],
    '14': [ ' ', 'fas fa-square black-strips', ],
    '15': [ ' ', 'fas fa-star black-strips', ],
    '16': [ ' ', 'fas fa-arrow-left black-strips', ],
    '17': [ ' ', 'fas fa-arrow-up black-strips', ],
    '18': [ ' ', 'fas fa-arrow-right black-strips', ],
    '19': [ ' ', 'fas fa-arrow-down black-strips', ],
    '1a': [ ' ', 'fas fa-plus red-strips', 'underline' ],
    '1b': [ ' ', 'fas fa-plus orange-strips', 'underline' ],
    '1c': [ ' ', 'fas fa-plus yellow-strips', 'underline' ],
    '1d': [ ' ', 'fas fa-plus green-strips', 'underline' ],
    '1e': [ ' ', 'fas fa-plus blue-strips', 'underline' ],
    '1f': [ ' ', 'fas fa-plus purple-strips', 'underline' ],
    '20': [ ' ', 'fas fa-plus gray-strips', ],
    '21': [ ' ', 'fas fa-circle gray-strips', ],
    '22': [ ' ', 'fas fa-heart gray-strips', ],
    '23': [ '▲', 'gray-strips', ],
    '24': [ ' ', 'fas fa-square gray-strips', ],
    '25': [ ' ', 'fas fa-star gray-strips', ],
    '26': [ ' ', 'fas fa-arrow-left gray-strips', ],
    '27': [ ' ', 'fas fa-arrow-up gray-strips', ],
    '28': [ ' ', 'fas fa-arrow-right gray-strips', ],
    '29': [ ' ', 'fas fa-arrow-down gray-strips', ],
    '2a': [ ' ', 'fas fa-heart red-strips', 'underline' ],
    '2b': [ ' ', 'fas fa-heart orange-strips', 'underline' ],
    '2c': [ ' ', 'fas fa-heart yellow-strips', 'underline' ],
    '2d': [ ' ', 'fas fa-heart green-strips', 'underline' ],
    '2e': [ ' ', 'fas fa-heart blue-strips', 'underline' ],
    '2f': [ ' ', 'fas fa-heart purple-strips', 'underline' ],
    '30': [ ' ', 'fas fa-plus white-strips', ],
    '31': [ ' ', 'fas fa-circle white-strips', ],
    '32': [ ' ', 'fas fa-heart white-strips', ],
    '33': [ '▲', 'white-strips', ],
    '34': [ ' ', 'fas fa-square white-strips', ],
    '35': [ ' ', 'fas fa-star white-strips', ],
    '36': [ ' ', 'fas fa-arrow-left white-strips', ],
    '37': [ ' ', 'fas fa-arrow-up white-strips', ],
    '38': [ ' ', 'fas fa-arrow-right white-strips', ],
    '39': [ ' ', 'fas fa-arrow-down white-strips', ],
    '3a': [ '▲', 'red-strips', 'underline' ],
    '3b': [ '▲', 'orange-strips', 'underline' ],
    '3c': [ '▲', 'yellow-strips', 'underline' ],
    '3d': [ '▲', 'green-strips', 'underline' ],
    '3e': [ '▲', 'blue-strips', 'underline' ],
    '3f': [ '▲', 'purple-strips', 'underline' ],
    '40': [ ' ', 'fas fa-yin-yang purple-strips', ],
    '41': [ ' ', 'fas fa-umbrella purple-strips', ],
    '42': [ ' ', 'fas fa-phone purple-strips', ],
    '43': [ ' ', 'fas fa-moon purple-strips', ],
    '44': [ ' ', 'fas fa-sun purple-strips', ],
    '45': [ ' ', 'fas fa-tree purple-strips', ],
    '46': [ ' ', 'fas fa-cut purple-strips', ],
    '47': [ ' ', 'fas fa-volume-up purple-strips', ],
    '48': [ ' ', 'fas fa-music purple-strips', ],
    '49': [ ' ', 'fas fa-plane purple-strips', ],
    '4a': [ ' ', 'fas fa-square red-strips', 'underline' ],
    '4b': [ ' ', 'fas fa-square orange-strips', 'underline' ],
    '4c': [ ' ', 'fas fa-square yellow-strips', 'underline' ],
    '4d': [ ' ', 'fas fa-square green-strips', 'underline' ],
    '4e': [ ' ', 'fas fa-square blue-strips', 'underline' ],
    '4f': [ ' ', 'fas fa-square purple-strips', 'underline' ],
    '50': [ ' ', 'fas fa-yin-yang blue-strips', ],
    '51': [ ' ', 'fas fa-umbrella blue-strips', ],
    '52': [ ' ', 'fas fa-phone blue-strips', ],
    '53': [ ' ', 'fas fa-moon blue-strips', ],
    '54': [ ' ', 'fas fa-sun blue-strips', ],
    '55': [ ' ', 'fas fa-tree blue-strips', ],
    '56': [ ' ', 'fas fa-cut blue-strips', ],
    '57': [ ' ', 'fas fa-volume-up blue-strips', ],
    '58': [ ' ', 'fas fa-music blue-strips', ],
    '59': [ ' ', 'fas fa-plane blue-strips', ],
    '5a': [ ' ', 'fas fa-star red-strips', 'underline' ],
    '5b': [ ' ', 'fas fa-star orange-strips', 'underline' ],
    '5c': [ ' ', 'fas fa-star yellow-strips', 'underline' ],
    '5d': [ ' ', 'fas fa-star green-strips', 'underline' ],
    '5e': [ ' ', 'fas fa-star blue-strips', 'underline' ],
    '5f': [ ' ', 'fas fa-star purple-strips', 'underline' ],
    '60': [ ' ', 'fas fa-yin-yang green-strips', ],
    '61': [ ' ', 'fas fa-umbrella green-strips', ],
    '62': [ ' ', 'fas fa-phone green-strips', ],
    '63': [ ' ', 'fas fa-moon green-strips', ],
    '64': [ ' ', 'fas fa-sun green-strips', ],
    '65': [ ' ', 'fas fa-tree green-strips', ],
    '66': [ ' ', 'fas fa-cut green-strips', ],
    '67': [ ' ', 'fas fa-volume-up green-strips', ],
    '68': [ ' ', 'fas fa-music green-strips', ],
    '69': [ ' ', 'fas fa-plane green-strips', ],
    '6a': [ ' ', 'fas fa-arrow-left red-strips', 'underline' ],
    '6b': [ ' ', 'fas fa-arrow-left orange-strips', 'underline' ],
    '6c': [ ' ', 'fas fa-arrow-left yellow-strips', 'underline' ],
    '6d': [ ' ', 'fas fa-arrow-left green-strips', 'underline' ],
    '6e': [ ' ', 'fas fa-arrow-left blue-strips', 'underline' ],
    '6f': [ ' ', 'fas fa-arrow-left purple-strips', 'underline' ],
    '70': [ ' ', 'fas fa-yin-yang yellow-strips', ],
    '71': [ ' ', 'fas fa-umbrella yellow-strips', ],
    '72': [ ' ', 'fas fa-phone yellow-strips', ],
    '73': [ ' ', 'fas fa-moon yellow-strips', ],
    '74': [ ' ', 'fas fa-sun yellow-strips', ],
    '75': [ ' ', 'fas fa-tree yellow-strips', ],
    '76': [ ' ', 'fas fa-cut yellow-strips', ],
    '77': [ ' ', 'fas fa-volume-up yellow-strips', ],
    '78': [ ' ', 'fas fa-music yellow-strips', ],
    '79': [ ' ', 'fas fa-plane yellow-strips', ],
    '7a': [ ' ', 'fas fa-arrow-up red-strips', 'underline' ],
    '7b': [ ' ', 'fas fa-arrow-up orange-strips', 'underline' ],
    '7c': [ ' ', 'fas fa-arrow-up yellow-strips', 'underline' ],
    '7d': [ ' ', 'fas fa-arrow-up green-strips', 'underline' ],
    '7e': [ ' ', 'fas fa-arrow-up blue-strips', 'underline' ],
    '7f': [ ' ', 'fas fa-arrow-up purple-strips', 'underline' ],
    '80': [ ' ', 'fas fa-yin-yang orange-strips', ],
    '81': [ ' ', 'fas fa-umbrella orange-strips', ],
    '82': [ ' ', 'fas fa-phone orange-strips', ],
    '83': [ ' ', 'fas fa-moon orange-strips', ],
    '84': [ ' ', 'fas fa-sun orange-strips', ],
    '85': [ ' ', 'fas fa-tree orange-strips', ],
    '86': [ ' ', 'fas fa-cut orange-strips', ],
    '87': [ ' ', 'fas fa-volume-up orange-strips', ],
    '88': [ ' ', 'fas fa-music orange-strips', ],
    '89': [ ' ', 'fas fa-plane orange-strips', ],
    '8a': [ ' ', 'fas fa-arrow-right red-strips', 'underline' ],
    '8b': [ ' ', 'fas fa-arrow-right orange-strips', 'underline' ],
    '8c': [ ' ', 'fas fa-arrow-right yellow-strips', 'underline' ],
    '8d': [ ' ', 'fas fa-arrow-right green-strips', 'underline' ],
    '8e': [ ' ', 'fas fa-arrow-right blue-strips', 'underline' ],
    '8f': [ ' ', 'fas fa-arrow-right purple-strips', 'underline' ],
    '90': [ ' ', 'fas fa-yin-yang red-strips', ],
    '91': [ ' ', 'fas fa-umbrella red-strips', ],
    '92': [ ' ', 'fas fa-phone red-strips', ],
    '93': [ ' ', 'fas fa-moon red-strips', ],
    '94': [ ' ', 'fas fa-sun red-strips', ],
    '95': [ ' ', 'fas fa-tree red-strips', ],
    '96': [ ' ', 'fas fa-cut red-strips', ],
    '97': [ ' ', 'fas fa-volume-up red-strips', ],
    '98': [ ' ', 'fas fa-music red-strips', ],
    '99': [ ' ', 'fas fa-plane red-strips', ],
    '9a': [ ' ', 'fas fa-arrow-down red-strips', 'underline' ],
    '9b': [ ' ', 'fas fa-arrow-down orange-strips', 'underline' ],
    '9c': [ ' ', 'fas fa-arrow-down yellow-strips', 'underline' ],
    '9d': [ ' ', 'fas fa-arrow-down green-strips', 'underline' ],
    '9e': [ ' ', 'fas fa-arrow-down blue-strips', 'underline' ],
    '9f': [ ' ', 'fas fa-arrow-down purple-strips', 'underline' ],
    'a0': [ ' ', 'fas fa-circle red-strips', ],
    'a1': [ ' ', 'fas fa-plus red-strips', ],
    'a2': [ ' ', 'fas fa-heart red-strips', ],
    'a3': [ '▲', 'red-strips', ],
    'a4': [ ' ', 'fas fa-square red-strips', ],
    'a5': [ ' ', 'fas fa-star red-strips', ],
    'a6': [ ' ', 'fas fa-arrow-left red-strips', ],
    'a7': [ ' ', 'fas fa-arrow-up red-strips', ],
    'a8': [ ' ', 'fas fa-arrow-right red-strips', ],
    'a9': [ ' ', 'fas fa-arrow-down red-strips', ],
    'aa': [ ' ', 'fas fa-home red-strips', ],
    'ab': [ ' ', 'fas fa-car red-strips', ],
    'ac': [ ' ', 'fas fa-book red-strips', ],
    'ad': [ ' ', 'fas fa-coffee red-strips', ],
    'ae': [ ' ', 'fas fa-envelope red-strips', ],
    'af': [ ' ', 'fas fa-fire red-strips', ],
    'b0': [ ' ', 'fas fa-circle orange-strips', ],
    'b1': [ ' ', 'fas fa-plus orange-strips', ],
    'b2': [ ' ', 'fas fa-heart orange-strips', ],
    'b3': [ '▲', 'orange-strips', ],
    'b4': [ ' ', 'fas fa-square orange-strips', ],
    'b5': [ ' ', 'fas fa-star orange-strips', ],
    'b6': [ ' ', 'fas fa-arrow-left orange-strips', ],
    'b7': [ ' ', 'fas fa-arrow-up orange-strips', ],
    'b8': [ ' ', 'fas fa-arrow-right orange-strips', ],
    'b9': [ ' ', 'fas fa-arrow-down orange-strips', ],
    'ba': [ ' ', 'fas fa-home orange-strips', ],
    'bb': [ ' ', 'fas fa-car orange-strips', ],
    'bc': [ ' ', 'fas fa-book orange-strips', ],
    'bd': [ ' ', 'fas fa-coffee orange-strips', ],
    'be': [ ' ', 'fas fa-envelope orange-strips', ],
    'bf': [ ' ', 'fas fa-fire orange-strips', ],
    'c0': [ ' ', 'fas fa-circle yellow-strips', ],
    'c1': [ ' ', 'fas fa-plus yellow-strips', ],
    'c2': [ ' ', 'fas fa-heart yellow-strips', ],
    'c3': [ '▲', 'yellow-strips', ],
    'c4': [ ' ', 'fas fa-square yellow-strips', ],
    'c5': [ ' ', 'fas fa-star yellow-strips', ],
    'c6': [ ' ', 'fas fa-arrow-left yellow-strips', ],
    'c7': [ ' ', 'fas fa-arrow-up yellow-strips', ],
    'c8': [ ' ', 'fas fa-arrow-right yellow-strips', ],
    'c9': [ ' ', 'fas fa-arrow-down yellow-strips', ],
    'ca': [ ' ', 'fas fa-home yellow-strips', ],
    'cb': [ ' ', 'fas fa-car yellow-strips', ],
    'cc': [ ' ', 'fas fa-book yellow-strips', ],
    'cd': [ ' ', 'fas fa-coffee yellow-strips', ],
    'ce': [ ' ', 'fas fa-envelope yellow-strips', ],
    'cf': [ ' ', 'fas fa-fire yellow-strips', ],
    'd0': [ ' ', 'fas fa-circle green-strips', ],
    'd1': [ ' ', 'fas fa-plus green-strips', ],
    'd2': [ ' ', 'fas fa-heart green-strips', ],
    'd3': [ '▲', 'green-strips', ],
    'd4': [ ' ', 'fas fa-square green-strips', ],
    'd5': [ ' ', 'fas fa-star green-strips', ],
    'd6': [ ' ', 'fas fa-arrow-left green-strips', ],
    'd7': [ ' ', 'fas fa-arrow-up green-strips', ],
    'd8': [ ' ', 'fas fa-arrow-right green-strips', ],
    'd9': [ ' ', 'fas fa-arrow-down green-strips', ],
    'da': [ ' ', 'fas fa-home green-strips', ],
    'db': [ ' ', 'fas fa-car green-strips', ],
    'dc': [ ' ', 'fas fa-book green-strips', ],
    'dd': [ ' ', 'fas fa-coffee green-strips', ],
    'de': [ ' ', 'fas fa-envelope green-strips', ],
    'df': [ ' ', 'fas fa-fire green-strips', ],
    'e0': [ ' ', 'fas fa-circle blue-strips', ],
    'e1': [ ' ', 'fas fa-plus blue-strips', ],
    'e2': [ ' ', 'fas fa-heart blue-strips', ],
    'e3': [ '▲', 'blue-strips', ],
    'e4': [ ' ', 'fas fa-square blue-strips', ],
    'e5': [ ' ', 'fas fa-star blue-strips', ],
    'e6': [ ' ', 'fas fa-arrow-left blue-strips', ],
    'e7': [ ' ', 'fas fa-arrow-up blue-strips', ],
    'e8': [ ' ', 'fas fa-arrow-right blue-strips', ],
    'e9': [ ' ', 'fas fa-arrow-down blue-strips', ],
    'ea': [ ' ', 'fas fa-home blue-strips', ],
    'eb': [ ' ', 'fas fa-car blue-strips', ],
    'ec': [ ' ', 'fas fa-book blue-strips', ],
    'ed': [ ' ', 'fas fa-coffee blue-strips', ],
    'ee': [ ' ', 'fas fa-envelope blue-strips', ],
    'ef': [ ' ', 'fas fa-fire blue-strips', ],
    'f0': [ ' ', 'fas fa-circle purple-strips', ],
    'f1': [ ' ', 'fas fa-plus purple-strips', ],
    'f2': [ ' ', 'fas fa-heart purple-strips', ],
    'f3': [ '▲', 'purple-strips', ],
    'f4': [ ' ', 'fas fa-square purple-strips', ],
    'f5': [ ' ', 'fas fa-star purple-strips', ],
    'f6': [ ' ', 'fas fa-arrow-left purple-strips', ],
    'f7': [ ' ', 'fas fa-arrow-up purple-strips', ],
    'f8': [ ' ', 'fas fa-arrow-right purple-strips', ],
    'f9': [ ' ', 'fas fa-arrow-down purple-strips', ],
    'fa': [ ' ', 'fas fa-home purple-strips', ],
    'fb': [ ' ', 'fas fa-car purple-strips', ],
    'fc': [ ' ', 'fas fa-book purple-strips', ],
    'fd': [ ' ', 'fas fa-coffee purple-strips', ],
    'fe': [ ' ', 'fas fa-envelope purple-strips', ],
    'ff': [ ' ', 'fas fa-fire purple-strips', ],
  },
});
