// exported at 10/7/2018, 11:26:33 PM
'use strict';

addArrayHexList({
  name: 'Geometric & Common Shapes',
  author: 'Hus',
  comment: '#230 but with FA',
  number: '230A',
  data: {
    '00': [ ' ', 'fas fa-headphones purple', ],
    '01': [ ' ', 'fas fa-umbrella purple', ],
    '02': [ ' ', 'fas fa-phone purple', ],
    '03': [ ' ', 'fas fa-moon purple', ],
    '04': [ ' ', 'fas fa-lightbulb purple', ],
    '05': [ ' ', 'fas fa-tree purple', ],
    '06': [ ' ', 'fas fa-cut purple', ],
    '07': [ ' ', 'fas fa-volume-up purple', ],
    '08': [ ' ', 'fas fa-music purple', ],
    '09': [ ' ', 'fas fa-plane purple', ],
    '0a': [ ' ', 'fas fa-circle purple', ],
    '0b': [ ' ', 'fas fa-plus purple', ],
    '0c': [ ' ', 'fas fa-heart purple', ],
    '0d': [ '▲', 'purple', ],
    '0e': [ ' ', 'fas fa-square purple', ],
    '0f': [ ' ', 'fas fa-star purple', ],
    '10': [ ' ', 'fas fa-home purple', ],
    '11': [ ' ', 'fas fa-car purple', ],
    '12': [ ' ', 'fas fa-book purple', ],
    '13': [ ' ', 'fas fa-coffee purple', ],
    '14': [ ' ', 'fas fa-envelope purple', ],
    '15': [ ' ', 'fas fa-fire purple', ],
    '16': [ ' ', 'fas fa-bicycle purple', ],
    '17': [ ' ', 'fas fa-camera purple', ],
    '18': [ ' ', 'fas fa-utensils purple', ],
    '19': [ ' ', 'fas fa-user purple', ],
    '1a': [ ' ', 'fas fa-futbol purple', ],
    '1b': [ ' ', 'fas fa-bell purple', ],
    '1c': [ ' ', 'fas fa-thumbs-up purple', ],
    '1d': [ ' ', 'fas fa-truck purple', ],
    '1e': [ ' ', 'fas fa-bolt purple', ],
    '1f': [ ' ', 'fas fa-clock purple', ],
    '20': [ ' ', 'fas fa-headphones blue', ],
    '21': [ ' ', 'fas fa-umbrella blue', ],
    '22': [ ' ', 'fas fa-phone blue', ],
    '23': [ ' ', 'fas fa-moon blue', ],
    '24': [ ' ', 'fas fa-lightbulb blue', ],
    '25': [ ' ', 'fas fa-tree blue', ],
    '26': [ ' ', 'fas fa-cut blue', ],
    '27': [ ' ', 'fas fa-volume-up blue', ],
    '28': [ ' ', 'fas fa-music blue', ],
    '29': [ ' ', 'fas fa-plane blue', ],
    '2a': [ ' ', 'fas fa-circle blue', ],
    '2b': [ ' ', 'fas fa-plus blue', ],
    '2c': [ ' ', 'fas fa-heart blue', ],
    '2d': [ '▲', 'blue', ],
    '2e': [ ' ', 'fas fa-square blue', ],
    '2f': [ ' ', 'fas fa-star blue', ],
    '30': [ ' ', 'fas fa-home blue', ],
    '31': [ ' ', 'fas fa-car blue', ],
    '32': [ ' ', 'fas fa-book blue', ],
    '33': [ ' ', 'fas fa-coffee blue', ],
    '34': [ ' ', 'fas fa-envelope blue', ],
    '35': [ ' ', 'fas fa-fire blue', ],
    '36': [ ' ', 'fas fa-bicycle blue', ],
    '37': [ ' ', 'fas fa-camera blue', ],
    '38': [ ' ', 'fas fa-utensils blue', ],
    '39': [ ' ', 'fas fa-user blue', ],
    '3a': [ ' ', 'fas fa-futbol blue', ],
    '3b': [ ' ', 'fas fa-bell blue', ],
    '3c': [ ' ', 'fas fa-thumbs-up blue', ],
    '3d': [ ' ', 'fas fa-truck blue', ],
    '3e': [ ' ', 'fas fa-bolt blue', ],
    '3f': [ ' ', 'fas fa-clock blue', ],
    '40': [ ' ', 'fas fa-headphones black', ],
    '41': [ ' ', 'fas fa-umbrella black', ],
    '42': [ ' ', 'fas fa-phone black', ],
    '43': [ ' ', 'fas fa-moon black', ],
    '44': [ ' ', 'fas fa-lightbulb black', ],
    '45': [ ' ', 'fas fa-tree black', ],
    '46': [ ' ', 'fas fa-cut black', ],
    '47': [ ' ', 'fas fa-volume-up black', ],
    '48': [ ' ', 'fas fa-music black', ],
    '49': [ ' ', 'fas fa-plane black', ],
    '4a': [ ' ', 'fas fa-circle black', ],
    '4b': [ ' ', 'fas fa-plus black', ],
    '4c': [ ' ', 'fas fa-heart black', ],
    '4d': [ '▲', 'black', ],
    '4e': [ ' ', 'fas fa-square black', ],
    '4f': [ ' ', 'fas fa-star black', ],
    '50': [ ' ', 'fas fa-home black', ],
    '51': [ ' ', 'fas fa-car black', ],
    '52': [ ' ', 'fas fa-book black', ],
    '53': [ ' ', 'fas fa-coffee black', ],
    '54': [ ' ', 'fas fa-envelope black', ],
    '55': [ ' ', 'fas fa-fire black', ],
    '56': [ ' ', 'fas fa-bicycle black', ],
    '57': [ ' ', 'fas fa-camera black', ],
    '58': [ ' ', 'fas fa-utensils black', ],
    '59': [ ' ', 'fas fa-user black', ],
    '5a': [ ' ', 'fas fa-futbol black', ],
    '5b': [ ' ', 'fas fa-bell black', ],
    '5c': [ ' ', 'fas fa-thumbs-up black', ],
    '5d': [ ' ', 'fas fa-truck black', ],
    '5e': [ ' ', 'fas fa-bolt black', ],
    '5f': [ ' ', 'fas fa-clock black', ],
    '60': [ ' ', 'fas fa-headphones green', ],
    '61': [ ' ', 'fas fa-umbrella green', ],
    '62': [ ' ', 'fas fa-phone green', ],
    '63': [ ' ', 'fas fa-moon green', ],
    '64': [ ' ', 'fas fa-lightbulb green', ],
    '65': [ ' ', 'fas fa-tree green', ],
    '66': [ ' ', 'fas fa-cut green', ],
    '67': [ ' ', 'fas fa-volume-up green', ],
    '68': [ ' ', 'fas fa-music green', ],
    '69': [ ' ', 'fas fa-plane green', ],
    '6a': [ ' ', 'fas fa-circle green', ],
    '6b': [ ' ', 'fas fa-plus green', ],
    '6c': [ ' ', 'fas fa-heart green', ],
    '6d': [ '▲', 'green', ],
    '6e': [ ' ', 'fas fa-square green', ],
    '6f': [ ' ', 'fas fa-star green', ],
    '70': [ ' ', 'fas fa-home green', ],
    '71': [ ' ', 'fas fa-car green', ],
    '72': [ ' ', 'fas fa-book green', ],
    '73': [ ' ', 'fas fa-coffee green', ],
    '74': [ ' ', 'fas fa-envelope green', ],
    '75': [ ' ', 'fas fa-fire green', ],
    '76': [ ' ', 'fas fa-bicycle green', ],
    '77': [ ' ', 'fas fa-camera green', ],
    '78': [ ' ', 'fas fa-utensils green', ],
    '79': [ ' ', 'fas fa-user green', ],
    '7a': [ ' ', 'fas fa-futbol green', ],
    '7b': [ ' ', 'fas fa-bell green', ],
    '7c': [ ' ', 'fas fa-thumbs-up green', ],
    '7d': [ ' ', 'fas fa-truck green', ],
    '7e': [ ' ', 'fas fa-bolt green', ],
    '7f': [ ' ', 'fas fa-clock green', ],
    '80': [ ' ', 'fas fa-yin-yang orange', ],
    '81': [ ' ', 'fas fa-umbrella orange', ],
    '82': [ ' ', 'fas fa-phone orange', ],
    '83': [ ' ', 'fas fa-moon orange', ],
    '84': [ ' ', 'fas fa-sun orange', ],
    '85': [ ' ', 'fas fa-tree orange', ],
    '86': [ ' ', 'fas fa-cut orange', ],
    '87': [ ' ', 'fas fa-volume-up orange', ],
    '88': [ ' ', 'fas fa-music orange', ],
    '89': [ ' ', 'fas fa-plane orange', ],
    '8a': [ ' ', 'fas fa-arrow-right red', 'underline' ],
    '8b': [ ' ', 'fas fa-arrow-right orange', 'underline' ],
    '8c': [ ' ', 'fas fa-thumbs-up green', ],
    '8d': [ ' ', 'fas fa-arrow-right green', 'underline' ],
    '8e': [ ' ', 'fas fa-arrow-right blue', 'underline' ],
    '8f': [ ' ', 'fas fa-arrow-right purple', 'underline' ],
    '90': [ ' ', 'fas fa-yin-yang red', ],
    '91': [ ' ', 'fas fa-umbrella red', ],
    '92': [ ' ', 'fas fa-phone red', ],
    '93': [ ' ', 'fas fa-moon red', ],
    '94': [ ' ', 'fas fa-sun red', ],
    '95': [ ' ', 'fas fa-tree red', ],
    '96': [ ' ', 'fas fa-cut red', ],
    '97': [ ' ', 'fas fa-volume-up red', ],
    '98': [ ' ', 'fas fa-music red', ],
    '99': [ ' ', 'fas fa-plane red', ],
    '9a': [ ' ', 'fas fa-arrow-down red', 'underline' ],
    '9b': [ ' ', 'fas fa-arrow-down orange', 'underline' ],
    '9c': [ ' ', 'fas fa-arrow-down yellow', 'underline' ],
    '9d': [ ' ', 'fas fa-arrow-down green', 'underline' ],
    '9e': [ ' ', 'fas fa-arrow-down blue', 'underline' ],
    '9f': [ ' ', 'fas fa-arrow-down purple', 'underline' ],
    'a0': [ ' ', 'fas fa-circle red', ],
    'a1': [ ' ', 'fas fa-plus red', ],
    'a2': [ ' ', 'fas fa-heart red', ],
    'a3': [ '▲', 'red', ],
    'a4': [ ' ', 'fas fa-square red', ],
    'a5': [ ' ', 'fas fa-star red', ],
    'a6': [ ' ', 'fas fa-arrow-left red', ],
    'a7': [ ' ', 'fas fa-arrow-up red', ],
    'a8': [ ' ', 'fas fa-arrow-right red', ],
    'a9': [ ' ', 'fas fa-arrow-down red', ],
    'aa': [ ' ', 'fas fa-home red', ],
    'ab': [ ' ', 'fas fa-car red', ],
    'ac': [ ' ', 'fas fa-book red', ],
    'ad': [ ' ', 'fas fa-coffee red', ],
    'ae': [ ' ', 'fas fa-envelope red', ],
    'af': [ ' ', 'fas fa-fire red', ],
    'b0': [ ' ', 'fas fa-circle orange', ],
    'b1': [ ' ', 'fas fa-plus orange', ],
    'b2': [ ' ', 'fas fa-heart orange', ],
    'b3': [ '▲', 'orange', ],
    'b4': [ ' ', 'fas fa-square orange', ],
    'b5': [ ' ', 'fas fa-star orange', ],
    'b6': [ ' ', 'fas fa-arrow-left orange', ],
    'b7': [ ' ', 'fas fa-arrow-up orange', ],
    'b8': [ ' ', 'fas fa-arrow-right orange', ],
    'b9': [ ' ', 'fas fa-arrow-down orange', ],
    'ba': [ ' ', 'fas fa-home orange', ],
    'bb': [ ' ', 'fas fa-car orange', ],
    'bc': [ ' ', 'fas fa-book orange', ],
    'bd': [ ' ', 'fas fa-coffee orange', ],
    'be': [ ' ', 'fas fa-envelope orange', ],
    'bf': [ ' ', 'fas fa-fire orange', ],
    'c0': [ ' ', 'fas fa-circle yellow', ],
    'c1': [ ' ', 'fas fa-plus yellow', ],
    'c2': [ ' ', 'fas fa-heart yellow', ],
    'c3': [ '▲', 'yellow', ],
    'c4': [ ' ', 'fas fa-square yellow', ],
    'c5': [ ' ', 'fas fa-star yellow', ],
    'c6': [ ' ', 'fas fa-arrow-left yellow', ],
    'c7': [ ' ', 'fas fa-arrow-up yellow', ],
    'c8': [ ' ', 'fas fa-arrow-right yellow', ],
    'c9': [ ' ', 'fas fa-arrow-down yellow', ],
    'ca': [ ' ', 'fas fa-home yellow', ],
    'cb': [ ' ', 'fas fa-car yellow', ],
    'cc': [ ' ', 'fas fa-book yellow', ],
    'cd': [ ' ', 'fas fa-coffee yellow', ],
    'ce': [ ' ', 'fas fa-envelope yellow', ],
    'cf': [ ' ', 'fas fa-fire yellow', ],
    'd0': [ ' ', 'fas fa-circle green', ],
    'd1': [ ' ', 'fas fa-plus green', ],
    'd2': [ ' ', 'fas fa-heart green', ],
    'd3': [ '▲', 'green', ],
    'd4': [ ' ', 'fas fa-square green', ],
    'd5': [ ' ', 'fas fa-star green', ],
    'd6': [ ' ', 'fas fa-arrow-left green', ],
    'd7': [ ' ', 'fas fa-arrow-up green', ],
    'd8': [ ' ', 'fas fa-arrow-right green', ],
    'd9': [ ' ', 'fas fa-arrow-down green', ],
    'da': [ ' ', 'fas fa-home green', ],
    'db': [ ' ', 'fas fa-car green', ],
    'dc': [ ' ', 'fas fa-book green', ],
    'dd': [ ' ', 'fas fa-coffee green', ],
    'de': [ ' ', 'fas fa-envelope green', ],
    'df': [ ' ', 'fas fa-fire green', ],
    'e0': [ ' ', 'fas fa-circle blue', ],
    'e1': [ ' ', 'fas fa-plus blue', ],
    'e2': [ ' ', 'fas fa-heart blue', ],
    'e3': [ '▲', 'blue', ],
    'e4': [ ' ', 'fas fa-square blue', ],
    'e5': [ ' ', 'fas fa-star blue', ],
    'e6': [ ' ', 'fas fa-arrow-left blue', ],
    'e7': [ ' ', 'fas fa-arrow-up blue', ],
    'e8': [ ' ', 'fas fa-arrow-right blue', ],
    'e9': [ ' ', 'fas fa-arrow-down blue', ],
    'ea': [ ' ', 'fas fa-home blue', ],
    'eb': [ ' ', 'fas fa-car blue', ],
    'ec': [ ' ', 'fas fa-book blue', ],
    'ed': [ ' ', 'fas fa-coffee blue', ],
    'ee': [ ' ', 'fas fa-envelope blue', ],
    'ef': [ ' ', 'fas fa-fire blue', ],
    'f0': [ ' ', 'fas fa-circle purple', ],
    'f1': [ ' ', 'fas fa-plus purple', ],
    'f2': [ ' ', 'fas fa-heart purple', ],
    'f3': [ '▲', 'purple', ],
    'f4': [ ' ', 'fas fa-square purple', ],
    'f5': [ ' ', 'fas fa-star purple', ],
    'f6': [ ' ', 'fas fa-arrow-left purple', ],
    'f7': [ ' ', 'fas fa-arrow-up purple', ],
    'f8': [ ' ', 'fas fa-arrow-right purple', ],
    'f9': [ ' ', 'fas fa-arrow-down purple', ],
    'fa': [ ' ', 'fas fa-home purple', ],
    'fb': [ ' ', 'fas fa-car purple', ],
    'fc': [ ' ', 'fas fa-book purple', ],
    'fd': [ ' ', 'fas fa-coffee purple', ],
    'fe': [ ' ', 'fas fa-envelope purple', ],
    'ff': [ ' ', 'fas fa-fire purple', ],
  },
});
